# Pandas — Part 1
## Introduction, Series and DataFrames

Pandas is a Python library used for working with structured and tabular data.

It is widely used in:

- Data Science
- Data Analysis
- Machine Learning
- Data Cleaning
- Exploratory Data Analysis (EDA)

Examples of data that can be handled using Pandas:

- Student records
- Customer data
- Sales data
- Employee information
- House prices
- Financial datasets
- Machine Learning datasets

Pandas mainly provides two important data structures:

1. Series
2. DataFrame

In [ ]:
import numpy as np
import pandas as pd

## 1. Pandas Series

A **Series** is a one-dimensional labeled data structure.

It can be thought of as:

NumPy Array + Labels

A Series contains:

- Values
- Index labels

By default, Pandas assigns indexes starting from `0`.

In [ ]:
marks = pd.Series([75, 82, 91, 68, 88])

print(marks)

0    75
1    82
2    91
3    68
4    88
dtype: int64

## 2. Accessing Series Elements

A Series can be accessed using its index.

For example:

- Index `0` → first value
- Index `1` → second value
- Index `2` → third value

In [ ]:
marks = pd.Series([75, 82, 91, 68, 88])

print(marks[0])
print(marks[2])
print(marks[4])

75
91
88

## 3. Custom Index

We can provide our own labels instead of using the default numerical index.

This is useful when the labels have meaning, such as:

- Student names
- Product IDs
- Dates
- Employee IDs

In [ ]:
marks = pd.Series(
    [75, 82, 91, 68, 88],
    index=["A", "B", "C", "D", "E"]
)

print(marks)

A    75
B    82
C    91
D    68
E    88
dtype: int64

## 4. Accessing Data Using Custom Index

When a Series has custom indexes, we can use those labels to access values.

In [ ]:
print(marks["A"])
print(marks["C"])
print(marks["E"])

75
91
88

## 5. Creating a Series from a Dictionary

A Python dictionary can be directly converted into a Pandas Series.

The:

- Dictionary keys become the Series indexes.
- Dictionary values become the Series values.

In [ ]:
marks = {
    "Rahul": 75,
    "Amit": 82,
    "Priya": 91,
    "Neha": 68
}

marks_series = pd.Series(marks)

print(marks_series)

Rahul    75
Amit     82
Priya    91
Neha     68
dtype: int64

## 6. Series Properties

Important Series properties include:

- `shape` → dimensions of the Series
- `size` → total number of elements
- `ndim` → number of dimensions
- `dtype` → data type of the values

In [ ]:
marks = pd.Series([75, 82, 91, 68, 88])

print("Shape:", marks.shape)
print("Size:", marks.size)
print("Dimensions:", marks.ndim)
print("Data Type:", marks.dtype)

Shape: (5,)
Size: 5
Dimensions: 1
Data Type: int64

## 7. Mathematical Operations on Series

Pandas Series support vectorized mathematical operations.

Operations can be performed directly on the entire Series without writing a loop.

In [ ]:
marks = pd.Series([75, 82, 91, 68, 88])

print("Original:")
print(marks)

print("\nAdded 5:")
print(marks + 5)

print("\nMultiplied by 2:")
print(marks * 2)

print("\nDivided by 2:")
print(marks / 2)

Original:
0    75
1    82
2    91
3    68
4    88
dtype: int64

Added 5:
0    80
1    87
2    96
3    73
4    93
dtype: int64

Multiplied by 2:
0    150
1    164
2    182
3    136
4    176
dtype: int64

Divided by 2:
0    37.5
1    41.0
2    45.5
3    34.0
4    44.0
dtype: float64

## 8. Statistical Operations on Series

Pandas provides built-in methods for common statistical calculations.

Important methods include:

- `mean()`
- `median()`
- `min()`
- `max()`
- `sum()`
- `std()`
- `var()`

These are frequently used during Data Analysis and EDA.

In [ ]:
marks = pd.Series([75, 82, 91, 68, 88])

print("Mean:", marks.mean())
print("Median:", marks.median())
print("Minimum:", marks.min())
print("Maximum:", marks.max())
print("Sum:", marks.sum())
print("Standard Deviation:", marks.std())
print("Variance:", marks.var())

Mean: 80.8
Median: 82.0
Minimum: 68
Maximum: 91
Sum: 404
Standard Deviation: 9.418067742376882
Variance: 88.69999999999999

## 9. Filtering a Series

A Series can be filtered using a condition.

The general pattern is:

```python
series[condition]

In [ ]:


marks = pd.Series([45, 67, 89, 32, 76, 91, 55, 84])

high_scores = marks[marks > 70]

print(high_scores)

2    89
4    76
5    91
7    84
dtype: int64

# DataFrame

A **DataFrame** is a two-dimensional labeled data structure.

It can be thought of as a table containing:

- Rows
- Columns
- Index
- Values

For Data Science, the DataFrame is the most commonly used Pandas structure.

Example:

| Name | Age | Marks |
|---|---:|---:|
| Rahul | 21 | 78 |
| Amit | 22 | 85 |
| Priya | 20 | 92 |
| Neha | 21 | 74 |

Here:

- Each column represents a variable or feature.
- Each row represents an observation.

In [ ]:
data = {
    "Name": ["Rahul", "Amit", "Priya", "Neha"],
    "Age": [21, 22, 20, 21],
    "Marks": [78, 85, 92, 74]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0  Rahul   21     78
1   Amit   22     85
2  Priya   20     92
3   Neha   21     74

## 10. DataFrame Shape

The `shape` property returns:

```text
(number of rows, number of columns)

(4, 3)

In [ ]:

print(df.shape)

(4, 3)

## 11. Rows and Columns

A DataFrame is organized as:

```text
Rows    → Observations
Columns → Variables / Features

For example, in a student dataset:

-Age

-Study_Hours

-Attendance

-Marks

In [ ]:

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 4
Number of columns: 3

## 12. Column Names

The `columns` property returns the names of all columns in the DataFrame.

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
print(df.columns.tolist())

['Name', 'Age', 'Marks']

## 13. DataFrame Index

Every DataFrame has an index.

By default, Pandas creates a numerical index:

```text
0
1
2
3
...

In [ ]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

## 14. Data Types

The `dtypes` property shows the data type of every column.

Understanding data types is important in Data Science because different types of data require different preprocessing techniques.

For example:

- Numerical columns → suitable for mathematical operations
- Text columns → usually require encoding or text processing
- Date columns → often require date/time processing

In [ ]:
print(df.dtypes)

Name     object
Age       int64
Marks     int64
dtype: object

## 15. Selecting a Single Column

A single column can be selected using:

```python
df["column_name"]

In [ ]:
print(df["Marks"])

0    78
1    85
2    92
3    74
Name: Marks, dtype: int64

In [ ]:
print(type(df["Marks"]))

<class 'pandas.core.series.Series'>

## 16. Selecting Multiple Columns

Multiple columns can be selected by passing a list of column names.

Selecting multiple columns returns a DataFrame.

In [ ]:
print(df[["Name", "Marks"]])

    Name  Marks
0  Rahul     78
1   Amit     85
2  Priya     92
3   Neha     74

## 17. Creating a New Column

A new column can be created by assigning values to a new column name.

This is one of the most common operations in Data Preparation and Feature Engineering.

In [ ]:
df["Passed"] = df["Marks"] >= 40

print(df)

    Name  Age  Marks  Passed
0  Rahul   21     78    True
1   Amit   22     85    True
2  Priya   20     92    True
3   Neha   21     74    True

## 18. Creating a Numerical Target

Machine Learning models commonly work with numerical target labels.

We can convert:

```text
True  → 1
False → 0

In [ ]:
df["Passed"] = (df["Marks"] >= 40).astype(int)

print(df)

    Name  Age  Marks  Passed
0  Rahul   21     78       1
1   Amit   22     85       1
2  Priya   20     92       1
3   Neha   21     74       1

## 19. Basic DataFrame Statistics

We can calculate statistics for individual columns.

Common operations include:

- Mean
- Minimum
- Maximum
- Median
- Standard deviation

In [ ]:
print("Average Age:", df["Age"].mean())
print("Average Marks:", df["Marks"].mean())

print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Age: 21.0
Average Marks: 82.25
Highest Marks: 92
Lowest Marks: 74

## 20. `describe()`

`describe()` provides a statistical summary of numerical columns.

It commonly includes:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

This is one of the first functions commonly used when exploring a new dataset.

In [ ]:
print(df.describe())

             Age      Marks  Passed
count   4.000000   4.000000     4.0
mean   21.000000  82.250000     1.0
std     0.816497   7.932003     0.0
min    20.000000  74.000000     1.0
25%    20.750000  77.000000     1.0
50%    21.000000  81.500000     1.0
75%    21.250000  86.750000     1.0
max    22.000000  92.000000     1.0

# Practical Data Science Example

Let's create a student dataset containing features that could later be used for Machine Learning.

Columns:

- Student
- Age
- Study_Hours
- Attendance
- Marks

In [ ]:
data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 22, 20, 23],
    "Study_Hours": [4, 6, 8, 3, 7],
    "Attendance": [75, 82, 91, 65, 88],
    "Marks": [62, 74, 89, 55, 84]
}

students = pd.DataFrame(data)

print(students)

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84

## 21. Filtering DataFrame Rows

We can select rows that satisfy a condition.

General pattern:

```python
df[condition]

In [ ]:
high_performers = students[
    students["Marks"] > 75
]

print(high_performers)

  Student  Age  Study_Hours  Attendance  Marks
2       C   22            8          91     89
4       E   23            7          88     84

## 22. Multiple Conditions

Multiple conditions can be combined using:

- `&` → AND
- `|` → OR

Each condition should be enclosed in parentheses.

Example:

```text
Study Hours > 5
AND
Attendance > 80

In [ ]:
result = students[
    (students["Study_Hours"] > 5) &
    (students["Attendance"] > 80)
]

print(result)

  Student  Age  Study_Hours  Attendance  Marks
1       B   21            6          82     74
2       C   22            8          91     89
4       E   23            7          88     84

## 23. Creating Features for Machine Learning

Pandas can be used to prepare the feature matrix `X` and target variable `y`.

For example, we can select:

```text
Age
Study Hours
Attendance

In [ ]:
X = students[
    ["Age", "Study_Hours", "Attendance"]
]

y = students["Marks"]

print("X:")
print(X)

print("\ny:")
print(y)

X:
   Age  Study_Hours  Attendance
0   20            4          75
1   21            6          82
2   22            8          91
3   20            3          65
4   23            7          88

y:
0    62
1    74
2    89
3    55
4    84
Name: Marks, dtype: int64

# NumPy vs Pandas

NumPy is primarily focused on numerical arrays and mathematical operations.

Pandas is designed for structured and tabular data.

```text
NumPy
  ↓
Numerical Arrays
  ↓
Mathematical Computation



Pandas
  ↓
Series + DataFrame
  ↓
Tabular Data
  ↓
Cleaning + Analysis + Preparation


---

### Markdown Cell

```markdown
# Part 1 Summary

In this section, we learned:

- What Pandas is
- Why Pandas is used in Data Science
- Pandas Series
- Creating Series
- Custom indexes
- Series from dictionaries
- Series properties
- Series mathematical operations
- Series statistics
- Series filtering
- DataFrames
- Creating DataFrames
- DataFrame shape
- Rows and columns
- Column names
- Index
- Data types
- Selecting columns
- Creating new columns
- Boolean filtering
- Multiple conditions
- Basic feature matrix `X`
- Target variable `y`

## Next Part

In the next section, we will learn how to **load and inspect real datasets**:

- Reading CSV files
- Reading Excel files
- `head()`
- `tail()`
- `sample()`
- `shape`
- `columns`
- `index`
- `dtypes`
- `info()`
- `describe()`

These operations will prepare us to work with the real Kaggle dataset later.

# Pandas — Part 2
## Loading and Inspecting Datasets

In Data Science, the first step after obtaining a dataset is to understand its structure.

A typical workflow is:

```text
Load Dataset
     ↓
Inspect Dataset
     ↓
Understand Columns
     ↓
Check Data Types
     ↓
Check Missing Values
     ↓
Analyze Statistics
     ↓
Clean Data
     ↓
Feature Engineering
     ↓
Machine Learning

In [ ]:


import numpy as np
import pandas as pd

## 1. Creating a Small Dataset

Before working with a large real-world dataset, let's create a small dataset to understand the basic Pandas inspection functions.

Suppose we have student data containing:

- Student
- Age
- Study Hours
- Attendance
- Marks

In [ ]:
data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 22, 20, 23],
    "Study_Hours": [4, 6, 8, 3, 7],
    "Attendance": [75, 82, 91, 65, 88],
    "Marks": [62, 74, 89, 55, 84]
}

df = pd.DataFrame(data)

df

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84

## 2. `head()`

`head()` displays the first few rows of a DataFrame.

By default, it displays the first 5 rows.

This is one of the first commands you should use after loading a dataset.

You can also specify the number of rows you want to see.

In [ ]:
df.head()

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84

In [ ]:
df.head(3)

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89

## 3. `tail()`

`tail()` displays the last few rows of a DataFrame.

This is useful for checking the end of a dataset and verifying whether the data appears consistent throughout the file.

In [ ]:
df.tail()

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84

In [ ]:
df.tail(2)

  Student  Age  Study_Hours  Attendance  Marks
3       D   20            3          65     55
4       E   23            7          88     84

## 4. `sample()`

`sample()` randomly selects rows from a DataFrame.

This can be useful when we want to inspect random observations instead of only looking at the beginning or end of the dataset.

In [ ]:
df.sample(3)

  Student  Age  Study_Hours  Attendance  Marks
2       C   22            8          91     89
4       E   23            7          88     84
0       A   20            4          75     62

## 5. Checking the Shape

The `shape` property tells us the number of rows and columns.

The result has the form:

```text
(rows, columns)

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Shape:", df.shape)

Rows: 5
Columns: 5
Shape: (5, 5)

## 6. Checking Column Names

The `columns` property gives us the names of all columns.

This is important because column names are used when selecting, filtering, modifying, and analyzing data.

In [ ]:
print(df.columns)

Index(['Student', 'Age', 'Study_Hours', 'Attendance', 'Marks'], dtype='object')

## 8. Checking Data Types

The `dtypes` property shows the data type of every column.

Typical data types include:

- `int64` → integers
- `float64` → decimal numbers
- `object` → commonly text/string data
- `bool` → True/False
- `datetime64` → date/time data

Understanding data types is important because different types require different processing techniques.

In [ ]:
df.dtypes

Student        object
Age             int64
Study_Hours     int64
Attendance      int64
Marks           int64
dtype: object

## 9. Using `info()`

`info()` provides a compact overview of the DataFrame.

It shows:

- Number of rows
- Column names
- Number of non-null values
- Data types
- Approximate memory usage

This is one of the most important commands when working with a new dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student      5 non-null      object
 1   Age          5 non-null      int64
 2   Study_Hours  5 non-null      int64
 3   Attendance   5 non-null      int64
 4   Marks        5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

## 10. Using `describe()`

`describe()` provides statistical information about numerical columns.

It commonly includes:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

This gives us an initial understanding of the numerical data.

In [ ]:
df.describe()

            Age  Study_Hours  Attendance      Marks
count   5.00000     5.000000    5.000000   5.000000
mean   21.20000     5.600000   80.200000  72.800000
std     1.30384     2.073644   10.473777  14.342245
min    20.00000     3.000000   65.000000  55.000000
25%    20.00000     4.000000   75.000000  62.000000
50%    21.00000     6.000000   82.000000  74.000000
75%    22.00000     7.000000   88.000000  84.000000
max    23.00000     8.000000   91.000000  89.000000

## 11. Describing Categorical Columns

By default, `describe()` focuses mainly on numerical columns.

We can also inspect categorical columns.

For example, we can use:

```python
df.describe(include="object")

In [ ]:
df.describe(include="object")

       Student
count        5
unique       5
top          A
freq         1

## Kaggle API Authentication Using `getpass`

For real-world datasets, we can use the Kaggle API to download datasets directly into Google Colab.

Instead of displaying the Kaggle API token in the notebook, we will use Python's `getpass` module to enter it securely.

The Kaggle API token will be entered during runtime and will not be displayed while typing.

> **Important:** Never hard-code your Kaggle API token directly into a notebook or upload it to GitHub.

In [99]:
!pip install -q kaggle

### Entering the Kaggle API Token

The Kaggle API token can be entered securely using `getpass`.

The input will not be displayed on the screen.

In [100]:
from getpass import getpass
import os

kaggle_token = getpass("Enter your Kaggle API token: ")

os.environ["KAGGLE_API_TOKEN"] = kaggle_token

del kaggle_token

Enter your Kaggle API token: ··········

### Configuring the Kaggle API

The Kaggle API expects the authentication token to be available through the Kaggle configuration.

We will create the required configuration directory and store the token during the current Colab session.

In [101]:
!kaggle competitions download -c titanic

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
titanic.zip: Skipping, found more recently modified local copy (use --force to force download)

In [102]:
!unzip -o titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

### Loading the Dataset with Pandas

The downloaded `train.csv` file can now be loaded using `pd.read_csv()`.

This is the point where Pandas starts working with a real-world dataset.

In [103]:
import pandas as pd

titanic = pd.read_csv("train.csv")

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 12. Checking the Dataset Shape

Before analyzing a dataset, determine how many observations and columns it contains.

In [104]:
print("Shape:", titanic.shape)
print("Rows:", titanic.shape[0])
print("Columns:", titanic.shape[1])

Shape: (891, 12)
Rows: 891
Columns: 12

## 13. Checking the Columns

Inspect the column names before performing any analysis.

This helps us understand what information is available in the dataset.

In [ ]:
print(titanic.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

## 14. Inspecting the First and Last Rows

Use `head()` and `tail()` to quickly inspect the dataset.

In [ ]:
print("First 5 rows:")
display(titanic.head())

print("Last 5 rows:")
display(titanic.tail())

First 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Last 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## 15. Randomly Inspecting the Dataset

A random sample can give us a better idea of how observations are distributed throughout the dataset.

In [ ]:
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
611,612,0,3,"Jardin, Mr. Jose Neto",male,NaN,0,0,SOTON/O.Q. 3101305,7.0500,NaN,S
637,638,0,2,"Collyer, Mr. Harvey",male,31.0,1,1,C.A. 31921,26.2500,NaN,S
296,297,0,3,"Hanna, Mr. Mansour",male,23.5,0,0,2693,7.2292,NaN,C
653,654,1,3,"O'Leary, Miss. Hanora ""Norah""",female,NaN,0,0,330919,7.8292,NaN,Q
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.0,1,1,PC 17756,83.1583,E49,C

## 16. Inspecting Data Types

Check the data types of all Titanic columns.

This is important because the dataset contains both numerical and categorical information.

In [ ]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## 17. Using `info()` on Real Data

Now use `info()` to understand:

- Dataset size
- Columns
- Non-null values
- Data types
- Potential missing values

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 18. Statistical Summary

Use `describe()` to get an initial statistical summary of the numerical columns.

This can help identify:

- Average values
- Data ranges
- Possible outliers
- Variation in the data

In [ ]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## 19. Inspecting Categorical Data

Some columns contain categorical information.

For example:

- `Sex`
- `Embarked`

We can inspect their summary using `describe(include="object")`.

In [ ]:
titanic.describe(include="object")

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

# Data Science Example

Suppose we want to understand the survival rate of passengers.

The `Survived` column contains:

```text
0 → Did not survive
1 → Survived

In [ ]:


survival_rate = titanic["Survived"].mean()

print("Survival Rate:", survival_rate)
print("Survival Percentage:", survival_rate * 100)

Survival Rate: 0.3838383838383838
Survival Percentage: 38.38383838383838

# AI / Machine Learning Example

For a Machine Learning problem, we often separate:

```text
Features → X
Target   → y

In [ ]:


features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

X = titanic[features]
y = titanic["Survived"]

print("X shape:", X.shape)
print("y shape:", y.shape)

# Data Science Inspection Checklist

Whenever you receive a new dataset, a useful initial checklist is:

```text
1. Load the dataset
2. Check shape
3. Check columns
4. View first rows
5. View last rows
6. View random samples
7. Check data types
8. Run info()
9. Run describe()
10. Inspect categorical columns
11. Check for missing values
12. Understand the target variable
13. Identify potential features


---

### Markdown Cell

```markdown
# Common Mistakes

## Mistake 1: Using `df.head` instead of `df.head()`

`head` is the method itself.

`head()` executes the method.

Correct:

```python
df.head()

Incorrect:

df.head
Mistake 2: Confusing shape with shape()

shape is a property, not a function.

Correct:

df.shape

Incorrect:

df.shape()
Mistake 3: Using the Wrong Column Name

Column names must match exactly.

For example:

df["Age"]

is different from:

df["age"]
Mistake 4: Forgetting Parentheses with Multiple Conditions

Incorrect:

df[df["Age"] > 20 & df["Fare"] > 50]

Correct:

df[(df["Age"] > 20) & (df["Fare"] > 50)]
Mistake 5: Treating object as Automatically Numerical

A column with object dtype often contains text or categorical values.

It should not automatically be passed to a Machine Learning model as a numerical feature.

Mistake 6: Training a Model Immediately

Do not immediately train a model after loading a dataset.

First understand:

Data Types
Missing Values
Duplicates
Outliers
Categorical Variables
Numerical Variables
Target Variable

Data preparation comes before model training.

Mistake 7: Exposing the Kaggle API Token

Never publish kaggle.json or its contents on:

GitHub
Public notebooks
Screenshots
Social media
Public repositories

Keep API credentials private.


---

### Markdown Cell

```markdown
# Part 2 Summary

In this section, we learned how to inspect datasets using Pandas.

Important functions and properties covered:

```text
head()
tail()
sample()
shape
columns
index
dtypes
info()
describe()

# Pandas — Part 3
## Selecting and Filtering Data

After loading and inspecting a dataset, we need to select the specific rows and columns required for analysis.

These operations are fundamental in:

- Data Analysis
- Exploratory Data Analysis (EDA)
- Data Cleaning
- Feature Engineering
- Machine Learning

In this section, we will learn:

1. Single-column selection
2. Multiple-column selection
3. `loc[]`
4. `iloc[]`
5. Boolean filtering
6. Multiple conditions using `&`
7. Multiple conditions using `|`
8. `isin()`
9. `between()`
10. Basic `X` and `y` preparation

We will first use a small synthetic dataset and then apply the same concepts to the real-world Titanic dataset.

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E", "F"],
    "Age": [20, 21, 22, 20, 23, 21],
    "Study_Hours": [4, 6, 8, 3, 7, 5],
    "Attendance": [75, 82, 91, 65, 88, 79],
    "Marks": [62, 74, 89, 55, 84, 71]
}

df = pd.DataFrame(data)

df

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84
5       F   21            5          79     71

## 1. Single-Column Selection

A single column can be selected using its column name.

The syntax is:

`df["column_name"]`

Selecting a single column returns a **Pandas Series**.

In [ ]:
marks = df["Marks"]

print(marks)
print(type(marks))

0    62
1    74
2    89
3    55
4    84
5    71
Name: Marks, dtype: int64
<class 'pandas.core.series.Series'>

## 2. Multiple-Column Selection

Multiple columns can be selected by passing a list of column names.

The result is a **Pandas DataFrame**.

This is useful when we only need a subset of the available variables.

In [ ]:
selected_data = df[
    ["Student", "Age", "Marks"]
]

selected_data

  Student  Age  Marks
0       A   20     62
1       B   21     74
2       C   22     89
3       D   20     55
4       E   23     84
5       F   21     71

## 3. `loc[]`

`loc[]` performs **label-based selection**.

The general syntax is:

`df.loc[row_label, column_label]`

It can be used to select:

- A specific row
- A specific value
- Multiple rows
- Specific rows and columns

In [ ]:
# Select the row with index label 0

df.loc[0]

Student         A
Age            20
Study_Hours     4
Attendance     75
Marks          62
Name: 0, dtype: object

In [ ]:
# Select a specific value

df.loc[2, "Marks"]

np.int64(89)

In [ ]:
# Select rows from index 1 through 3

df.loc[1:3]

  Student  Age  Study_Hours  Attendance  Marks
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55

In [ ]:
# Select specific rows and columns

df.loc[
    1:3,
    ["Student", "Marks"]
]

  Student  Marks
1       B     74
2       C     89
3       D     55

## 4. `iloc[]`

`iloc[]` performs **position-based selection**.

The general syntax is:

`df.iloc[row_position, column_position]`

Positions start from `0`.

The important difference is:

| Method | Based On |
|---|---|
| `loc[]` | Labels |
| `iloc[]` | Integer positions |

In [ ]:
# Select the first row

df.iloc[0]

Student         A
Age            20
Study_Hours     4
Attendance     75
Marks          62
Name: 0, dtype: object

In [ ]:
# Select the value at row position 2 and column position 4

df.iloc[2, 4]

np.int64(89)

In [ ]:
# Select rows at positions 1, 2 and 3

df.iloc[1:4]

  Student  Age  Study_Hours  Attendance  Marks
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55

In [ ]:
# Select rows 1 to 3 and columns 0 and 4

df.iloc[
    1:4,
    [0, 4]
]

  Student  Marks
1       B     74
2       C     89
3       D     55

## 5. Boolean Filtering

Boolean filtering allows us to select only rows that satisfy a condition.

The general pattern is:

`df[condition]`

For example, we can select students whose marks are greater than `75`.

In [ ]:
high_scorers = df[
    df["Marks"] > 75
]

high_scorers

  Student  Age  Study_Hours  Attendance  Marks
2       C   22            8          91     89
4       E   23            7          88     84

## 6. Multiple Conditions Using `&`

The `&` operator represents **AND**.

Both conditions must be true.

For example, select students who:

- Study for more than 5 hours
- AND have attendance greater than 80

In [ ]:
result = df[
    (df["Study_Hours"] > 5) &
    (df["Attendance"] > 80)
]

result

  Student  Age  Study_Hours  Attendance  Marks
1       B   21            6          82     74
2       C   22            8          91     89
4       E   23            7          88     84

## 7. Multiple Conditions Using `|`

The `|` operator represents **OR**.

At least one of the conditions must be true.

For example, select students who:

- Have marks greater than 85
- OR have attendance greater than 90

In [ ]:
result = df[
    (df["Marks"] > 85) |
    (df["Attendance"] > 90)
]

result

  Student  Age  Study_Hours  Attendance  Marks
2       C   22            8          91     89

## 8. `isin()`

`isin()` is useful when we want to check whether values belong to a specific list.

For example, we can select students whose age is either:

- 20
- 23

In [ ]:
result = df[
    df["Age"].isin([20, 23])
]

result

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
3       D   20            3          65     55
4       E   23            7          88     84

## 9. `between()`

`between()` is used to select values within a specified range.

For example, we can select students whose marks are between `70` and `85`.

By default, the boundary values are included.

In [ ]:
result = df[
    df["Marks"].between(70, 85)
]

result

  Student  Age  Study_Hours  Attendance  Marks
1       B   21            6          82     74
4       E   23            7          88     84
5       F   21            5          79     71

# 10. Basic `X` and `y` Preparation

In supervised Machine Learning, we generally separate the dataset into:

- `X` → Feature Matrix
- `y` → Target Variable

Suppose we want to predict student marks using:

- Age
- Study Hours
- Attendance

Then these three columns become our features.

`Marks` becomes the target.

The structure is:

X → Input Features

y → Target

In [ ]:
X = df[
    ["Age", "Study_Hours", "Attendance"]
]

y = df["Marks"]

print("Feature Matrix X:")
print(X)

print("\nTarget y:")
print(y)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

# Real-World Example — Titanic Dataset

We will now apply the same selection and filtering operations to the Titanic dataset downloaded from Kaggle.

The important columns include:

- `PassengerId`
- `Survived`
- `Pclass`
- `Name`
- `Sex`
- `Age`
- `SibSp`
- `Parch`
- `Fare`
- `Embarked`

The target variable is:

`Survived`

where:

- `0` → Did not survive
- `1` → Survived

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Single and Multiple Column Selection on Titanic

We can select specific columns from the real-world dataset.

For example:

- Passenger name
- Sex
- Age
- Fare
- Survival status

In [ ]:
titanic[
    ["Name", "Sex", "Age", "Fare", "Survived"]
].head()

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0

## Boolean Filtering on Titanic

We can filter passengers based on their characteristics.

For example, we can select only female passengers.

In [ ]:
female_passengers = titanic[
    titanic["Sex"] == "female"
]

female_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## Multiple Conditions on Titanic

We can combine multiple conditions.

For example, select passengers who were:

- Female
- In first class
- Paid a fare greater than 50

In [ ]:
result = titanic[
    (titanic["Sex"] == "female") &
    (titanic["Pclass"] == 1) &
    (titanic["Fare"] > 50)
]

result.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN

## Using `isin()` on Titanic

Suppose we want passengers from first or second class.

We can use `isin()` to check whether `Pclass` belongs to the list `[1, 2]`.

In [ ]:
result = titanic[
    titanic["Pclass"].isin([1, 2])
]

result.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

## Using `between()` on Titanic

We can also filter passengers based on a numerical range.

For example, find passengers whose fare was between 20 and 50.

In [ ]:
result = titanic[
    titanic["Fare"].between(20, 50)
]

result.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q

# AI / Machine Learning Example

Suppose we want to create a basic Machine Learning dataset for predicting passenger survival.

We can select numerical features such as:

- `Pclass`
- `Age`
- `SibSp`
- `Parch`
- `Fare`

The target is:

- `Survived`

At this stage, we are only selecting the data.

The selected dataset still requires preprocessing because real-world data can contain:

- Missing values
- Categorical variables
- Different data types

Those topics will be handled in later sections.

In [ ]:
features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

X_titanic = titanic[features]

y_titanic = titanic["Survived"]

print("Feature Matrix X:")
print(X_titanic.head())

print("\nTarget y:")
print(y_titanic.head())

print("\nX Shape:", X_titanic.shape)
print("y Shape:", y_titanic.shape)

# Data Science Example

Suppose we want to identify passengers who paid a high fare and were travelling in first class.

This type of filtering can be useful during Exploratory Data Analysis.

We can then investigate their:

- Survival rate
- Age distribution
- Gender distribution
- Family size
- Fare distribution

The filtering operation itself is only the first step of the analysis.

In [ ]:
high_value_passengers = titanic[
    (titanic["Pclass"] == 1) &
    (titanic["Fare"] > 100)
]

high_value_passengers.head()

# Common Mistakes

## 1. Using `and` Instead of `&`

For Pandas Series, use `&` for element-wise AND.

Do not use Python's `and`.

## 2. Using `or` Instead of `|`

For Pandas Series, use `|` for element-wise OR.

## 3. Forgetting Parentheses

Each condition should be enclosed in parentheses when using `&` or `|`.

## 4. Confusing `loc[]` and `iloc[]`

Remember:

`loc[]` → Labels

`iloc[]` → Integer positions

## 5. Forgetting Double Brackets

Single column:

`df["Marks"]`

Multiple columns:

`df[["Marks", "Age"]]`

## 6. Assuming Filtering Changes the Original DataFrame

A filtering operation normally creates a result.

It does not automatically modify the original DataFrame.

## 7. Ignoring Missing Values

Real-world datasets can contain missing values.

For example, Titanic contains missing values in columns such as `Age`.

Missing-value handling will be covered separately.

# Part 3 — Summary

We learned how to select and filter data using Pandas.

### Selection

- Single-column selection
- Multiple-column selection
- `loc[]`
- `iloc[]`

### Filtering

- Boolean filtering
- Multiple conditions using `&`
- Multiple conditions using `|`
- `isin()`
- `between()`

### Machine Learning

We also learned the basic structure:

`X` → Feature Matrix

`y` → Target Variable

### Real-World Application

We applied these operations to the Titanic dataset and created a basic feature matrix for a potential classification problem.

## Next Topic

# Pandas — Part 4
## Adding, Modifying, Renaming and Removing Data

The next section will introduce new concepts only:

- Creating new columns
- Calculated columns
- Modifying columns
- `assign()`
- `rename()`
- `drop()`
- `insert()`
- Reordering columns
- Feature Engineering
- Real-world Titanic feature creation
- AI/ML examples
- Common mistakes

# Pandas — Part 4
## Adding, Modifying, Renaming & Removing Data

In the previous section, we learned how to select and filter data.

Now we will learn how to **modify a DataFrame**.

Real-world datasets often require transformation before they can be used for:

- Data Analysis
- Exploratory Data Analysis (EDA)
- Feature Engineering
- Machine Learning

In this section, we will learn:

1. Creating new columns
2. Creating calculated columns
3. Creating columns using multiple columns
4. Modifying existing columns
5. Creating categorical features
6. Using `assign()`
7. Renaming columns
8. Dropping columns
9. Dropping rows
10. Inserting columns
11. Reordering columns
12. Feature Engineering
13. Real-world Titanic feature engineering
14. AI/ML applications
15. Common mistakes

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E", "F"],
    "Age": [20, 21, 22, 20, 23, 21],
    "Study_Hours": [4, 6, 8, 3, 7, 5],
    "Attendance": [75, 82, 91, 65, 88, 79],
    "Marks": [62, 74, 89, 55, 84, 71]
}

df = pd.DataFrame(data)

df

  Student  Age  Study_Hours  Attendance  Marks
0       A   20            4          75     62
1       B   21            6          82     74
2       C   22            8          91     89
3       D   20            3          65     55
4       E   23            7          88     84
5       F   21            5          79     71

## 1. Creating a New Column

A new column can be created by assigning a value to a new column name.

The new column can contain:

- A constant value
- Calculated values
- Boolean values
- Values derived from existing columns

Creating new columns is one of the most common operations in Data Science.

For example, we can create a `Passed` column based on whether a student's marks are at least 40.

The result will be:

- `1` → Passed
- `0` → Failed

This is also an example of creating a feature that can later be used in Machine Learning.

In [ ]:
df["Passed"] = (df["Marks"] >= 40).astype(int)

df

  Student  Age  Study_Hours  Attendance  Marks  Passed
0       A   20            4          75     62       1
1       B   21            6          82     74       1
2       C   22            8          91     89       1
3       D   20            3          65     55       1
4       E   23            7          88     84       1
5       F   21            5          79     71       1

## 2. Creating a Calculated Column

We can create a new column by performing a calculation on an existing column.

Suppose `Study_Hours` represents the number of hours a student studies.

We can convert it into minutes:

`Study_Minutes = Study_Hours × 60`

This is useful when we want the same information represented in a different form.

In [ ]:
df["Study_Minutes"] = df["Study_Hours"] * 60

df

  Student  Age  Study_Hours  Attendance  Marks  Passed  Study_Minutes
0       A   20            4          75     62       1            240
1       B   21            6          82     74       1            360
2       C   22            8          91     89       1            480
3       D   20            3          65     55       1            180
4       E   23            7          88     84       1            420
5       F   21            5          79     71       1            300

## 3. Creating a Column Using Multiple Columns

A new feature can be created using multiple existing columns.

Suppose we want to calculate a performance score using:

- Marks → 70%
- Attendance → 30%

The formula is:

`Performance_Score = Marks × 0.70 + Attendance × 0.30`

This is an example of **Feature Engineering**.

Feature Engineering means creating useful features from existing data.

In [ ]:
df["Performance_Score"] = (
    df["Marks"] * 0.70 +
    df["Attendance"] * 0.30
)

df

,Student,Age,Study_Hours,Attendance,Marks,Passed,Study_Minutes,Performance_Score
0,A,20,4,75,62,1,240,65.9
1,B,21,6,82,74,1,360,76.4
2,C,22,8,91,89,1,480,89.6
3,D,20,3,65,55,1,180,58.0
4,E,23,7,88,84,1,420,85.2
5,F,21,5,79,71,1,300,73.4

## 4. Modifying an Existing Column

An existing column can be transformed by assigning a new value to it.

For example, marks are currently represented from 0 to 100.

We can convert them into a decimal representation between 0 and 1.

Important:

When we assign the result back to the original column, the original values are replaced.

Therefore, when we want to preserve the original data, it is usually better to create a new column.

In [ ]:
df["Marks"] = df["Marks"] / 100

df

,Student,Age,Study_Hours,Attendance,Marks,Passed,Study_Minutes,Performance_Score
0,A,20,4,75,0.62,1,240,65.9
1,B,21,6,82,0.74,1,360,76.4
2,C,22,8,91,0.89,1,480,89.6
3,D,20,3,65,0.55,1,180,58.0
4,E,23,7,88,0.84,1,420,85.2
5,F,21,5,79,0.71,1,300,73.4

## Restoring the Original Marks

For the remaining examples, we want `Marks` to remain on a 0–100 scale.

We can restore the original values so that the following examples are easier to understand.

In [ ]:
df["Marks"] = df["Marks"] * 100

df

,Student,Age,Study_Hours,Attendance,Marks,Passed,Study_Minutes,Performance_Score
0,A,20,4,75,62.0,1,240,65.9
1,B,21,6,82,74.0,1,360,76.4
2,C,22,8,91,89.0,1,480,89.6
3,D,20,3,65,55.0,1,180,58.0
4,E,23,7,88,84.0,1,420,85.2
5,F,21,5,79,71.0,1,300,73.4

## 5. Creating Categorical Features

Sometimes numerical values are easier to understand when converted into categories.

For example:

- Marks >= 80 → Excellent
- Marks >= 60 → Good
- Marks >= 40 → Average
- Marks < 40 → Needs Improvement

This type of transformation is useful in:

- Data Analysis
- Reporting
- Exploratory Data Analysis
- Feature Engineering

We can use NumPy's `select()` to create the categories.

In [ ]:
conditions = [
    df["Marks"] >= 80,
    df["Marks"] >= 60,
    df["Marks"] >= 40
]

choices = [
    "Excellent",
    "Good",
    "Average"
]

df["Performance_Level"] = np.select(
    conditions,
    choices,
    default="Needs Improvement"
)

df

,Student,Age,Study_Hours,Attendance,Marks,Passed,Study_Minutes,Performance_Score,Performance_Level
0,A,20,4,75,62.0,1,240,65.9,Good
1,B,21,6,82,74.0,1,360,76.4,Good
2,C,22,8,91,89.0,1,480,89.6,Excellent
3,D,20,3,65,55.0,1,180,58.0,Average
4,E,23,7,88,84.0,1,420,85.2,Excellent
5,F,21,5,79,71.0,1,300,73.4,Good

## 6. Using `assign()`

`assign()` provides another way to create new columns.

It returns a new DataFrame containing the added or modified columns.

It is particularly useful when performing several transformations as part of a data-processing workflow.

One advantage is that it can make transformation pipelines easier to read.

In [ ]:
df = df.assign(
    Study_Days=df["Study_Hours"] / 2
)

df

,Student,Age,Study_Hours,Attendance,Marks,Passed,Study_Minutes,Performance_Score,Performance_Level,Study_Days
0,A,20,4,75,62.0,1,240,65.9,Good,2.0
1,B,21,6,82,74.0,1,360,76.4,Good,3.0
2,C,22,8,91,89.0,1,480,89.6,Excellent,4.0
3,D,20,3,65,55.0,1,180,58.0,Average,1.5
4,E,23,7,88,84.0,1,420,85.2,Excellent,3.5
5,F,21,5,79,71.0,1,300,73.4,Good,2.5

## 7. Renaming Columns

Column names can be changed using `rename()`.

Renaming is useful when:

- Names are unclear
- Names are inconsistent
- Names contain unnecessary spaces
- We want standardized naming
- We want names that are easier to use in code

For example, we can change:

`Student` → `Student_ID`

`Marks` → `Final_Marks`

In [ ]:
df = df.rename(
    columns={
        "Student": "Student_ID",
        "Marks": "Final_Marks"
    }
)

df

,Student_ID,Age,Study_Hours,Attendance,Final_Marks,Passed,Study_Minutes,Performance_Score,Performance_Level,Study_Days
0,A,20,4,75,62.0,1,240,65.9,Good,2.0
1,B,21,6,82,74.0,1,360,76.4,Good,3.0
2,C,22,8,91,89.0,1,480,89.6,Excellent,4.0
3,D,20,3,65,55.0,1,180,58.0,Average,1.5
4,E,23,7,88,84.0,1,420,85.2,Excellent,3.5
5,F,21,5,79,71.0,1,300,73.4,Good,2.5

## 8. Dropping Columns

Unnecessary columns can be removed using `drop()`.

A column may be removed because:

- It is irrelevant
- It contains duplicate information
- It is no longer required
- It is not useful for the current analysis

We should always understand a column before removing it.

Here, we will remove the temporary `Study_Days` column.

In [ ]:
df = df.drop(
    columns=["Study_Days"]
)

df

,Student_ID,Age,Study_Hours,Attendance,Final_Marks,Passed,Study_Minutes,Performance_Score,Performance_Level
0,A,20,4,75,62.0,1,240,65.9,Good
1,B,21,6,82,74.0,1,360,76.4,Good
2,C,22,8,91,89.0,1,480,89.6,Excellent
3,D,20,3,65,55.0,1,180,58.0,Average
4,E,23,7,88,84.0,1,420,85.2,Excellent
5,F,21,5,79,71.0,1,300,73.4,Good

## 9. Dropping Rows

Rows can also be removed using `drop()`.

We specify the index of the row that should be removed.

For demonstration, we will create a separate DataFrame so that our original dataset remains unchanged.

In [ ]:
df_without_first_row = df.drop(index=0)

df_without_first_row

,Student_ID,Age,Study_Hours,Attendance,Final_Marks,Passed,Study_Minutes,Performance_Score,Performance_Level
1,B,21,6,82,74.0,1,360,76.4,Good
2,C,22,8,91,89.0,1,480,89.6,Excellent
3,D,20,3,65,55.0,1,180,58.0,Average
4,E,23,7,88,84.0,1,420,85.2,Excellent
5,F,21,5,79,71.0,1,300,73.4,Good

## 10. Inserting a Column

`insert()` allows us to create a new column at a specific position.

The general structure is:

`df.insert(position, column_name, values)`

The position starts from `0`.

This is useful when the order of columns matters for readability or reporting.

In [ ]:
df.insert(
    2,
    "Study_Minutes_Copy",
    df["Study_Minutes"]
)

df

,Student_ID,Age,Study_Minutes_Copy,Study_Hours,Attendance,Final_Marks,Passed,Study_Minutes,Performance_Score,Performance_Level
0,A,20,240,4,75,62.0,1,240,65.9,Good
1,B,21,360,6,82,74.0,1,360,76.4,Good
2,C,22,480,8,91,89.0,1,480,89.6,Excellent
3,D,20,180,3,65,55.0,1,180,58.0,Average
4,E,23,420,7,88,84.0,1,420,85.2,Excellent
5,F,21,300,5,79,71.0,1,300,73.4,Good

## Removing the Demonstration Column

The previous column was created only to demonstrate `insert()`.

We can remove it using `drop()`.

In [ ]:
df = df.drop(
    columns=["Study_Minutes_Copy"]
)

df

,Student_ID,Age,Study_Hours,Attendance,Final_Marks,Passed,Study_Minutes,Performance_Score,Performance_Level
0,A,20,4,75,62.0,1,240,65.9,Good
1,B,21,6,82,74.0,1,360,76.4,Good
2,C,22,8,91,89.0,1,480,89.6,Excellent
3,D,20,3,65,55.0,1,180,58.0,Average
4,E,23,7,88,84.0,1,420,85.2,Excellent
5,F,21,5,79,71.0,1,300,73.4,Good

## 11. Reordering Columns

We can rearrange the columns into a specific order.

This can make a dataset easier to read and can be useful when preparing data for further processing.

We simply create a list containing the desired column order and use it to reorganize the DataFrame.

In [ ]:
column_order = [
    "Student_ID",
    "Age",
    "Study_Hours",
    "Study_Minutes",
    "Attendance",
    "Final_Marks",
    "Passed",
    "Performance_Score",
    "Performance_Level"
]

df = df[column_order]

df

,Student_ID,Age,Study_Hours,Study_Minutes,Attendance,Final_Marks,Passed,Performance_Score,Performance_Level
0,A,20,4,240,75,62.0,1,65.9,Good
1,B,21,6,360,82,74.0,1,76.4,Good
2,C,22,8,480,91,89.0,1,89.6,Excellent
3,D,20,3,180,65,55.0,1,58.0,Average
4,E,23,7,420,88,84.0,1,85.2,Excellent
5,F,21,5,300,79,71.0,1,73.4,Good

# Data Science Example
## Creating an Overall Performance Feature

Feature Engineering often combines multiple variables into a new feature.

Suppose we create an overall score using:

- Final Marks → 60%
- Attendance → 30%
- Study Hours → 10%

Because Study Hours can be on a different numerical scale, we will use a simple weighted formula for demonstration.

This is not necessarily the best statistical formula for a real model.

The important concept is how existing columns can be transformed into a new feature.

In [ ]:
df["Overall_Score"] = (
    df["Final_Marks"] * 0.60 +
    df["Attendance"] * 0.30 +
    df["Study_Hours"] * 2
)

df

/tmp/ipykernel_2724/1101080875.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Overall_Score"] = (

,Student_ID,Age,Study_Hours,Study_Minutes,Attendance,Final_Marks,Passed,Performance_Score,Performance_Level,Overall_Score
0,A,20,4,240,75,62.0,1,65.9,Good,67.7
1,B,21,6,360,82,74.0,1,76.4,Good,81.0
2,C,22,8,480,91,89.0,1,89.6,Excellent,96.7
3,D,20,3,180,65,55.0,1,58.0,Average,58.5
4,E,23,7,420,88,84.0,1,85.2,Excellent,90.8
5,F,21,5,300,79,71.0,1,73.4,Good,76.3

# AI / Machine Learning Example
## Creating a Classification Target

Suppose we want to classify students into:

- High Performer
- Not High Performer

We can define a simple rule:

`Overall_Score >= 70` → High Performer

`Overall_Score < 70` → Not High Performer

We can represent these classes numerically:

- `1` → High Performer
- `0` → Not High Performer

This creates a binary classification target.

In a real Machine Learning project, the target definition should be based on the actual business or academic problem rather than an arbitrary rule.

In [ ]:
df["High_Performer"] = (
    df["Overall_Score"] >= 70
).astype(int)

df

# Creating the Machine Learning Dataset

We can now separate the dataset into:

`X` → Input Features

`y` → Target Variable

For this example, we will use:

- Age
- Study Hours
- Attendance
- Performance Score
- Overall Score

as features.

The target will be `High_Performer`.

This creates the basic structure required for a supervised Machine Learning problem.

In [ ]:
X = df[
    [
        "Age",
        "Study_Hours",
        "Attendance",
        "Performance_Score",
        "Overall_Score"
    ]
]

y = df["High_Performer"]

print("Feature Matrix X:")
print(X)

print("\nTarget y:")
print(y)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

# Real-World Example
## Titanic Feature Engineering

Now we will apply the new concepts to the Titanic dataset downloaded from Kaggle.

The Titanic dataset contains information such as:

- Passenger class
- Age
- Sex
- Number of siblings/spouses
- Number of parents/children
- Fare
- Survival

We can create additional features from these existing columns.

This is a common step in real-world Machine Learning workflows.

We will create:

1. `Family_Size`
2. `Fare_Per_Person`
3. `Age_Group`

These features are derived from information already present in the dataset.

In [ ]:
# Make a copy so that the original Titanic DataFrame remains unchanged

titanic_features = titanic.copy()

titanic_features.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Creating `Family_Size`

The Titanic dataset contains:

- `SibSp` → siblings and spouses aboard
- `Parch` → parents and children aboard

We can combine these values to estimate the total family size.

The passenger themselves should also be counted.

Therefore:

`Family_Size = SibSp + Parch + 1`

This can be a useful feature because family size may have a relationship with survival behavior.

In [ ]:
titanic_features["Family_Size"] = (
    titanic_features["SibSp"] +
    titanic_features["Parch"] +
    1
)

titanic_features[
    ["SibSp", "Parch", "Family_Size"]
].head(10)

   SibSp  Parch  Family_Size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1
5      0      0            1
6      0      0            1
7      3      1            5
8      0      2            3
9      1      0            2

## Creating `Fare_Per_Person`

The `Fare` column represents the fare associated with a passenger.

We can calculate the approximate fare per family member:

`Fare_Per_Person = Fare / Family_Size`

This creates a new numerical feature that may provide information different from the original total fare.

In [ ]:
titanic_features["Fare_Per_Person"] = (
    titanic_features["Fare"] /
    titanic_features["Family_Size"]
)

titanic_features[
    ["Fare", "Family_Size", "Fare_Per_Person"]
].head(10)

      Fare  Family_Size  Fare_Per_Person
0   7.2500            2          3.62500
1  71.2833            2         35.64165
2   7.9250            1          7.92500
3  53.1000            2         26.55000
4   8.0500            1          8.05000
5   8.4583            1          8.45830
6  51.8625            1         51.86250
7  21.0750            5          4.21500
8  11.1333            3          3.71110
9  30.0708            2         15.03540

## Creating `Age_Group`

Age is a numerical variable.

For analysis, it can sometimes be useful to divide age into meaningful groups:

- Child
- Teenager
- Adult
- Senior

We can use `pd.cut()` to divide the numerical age values into intervals.

This creates a categorical variable from a numerical variable.

Note that categorical variables may require additional preprocessing before being passed directly to many Machine Learning algorithms.

In [105]:
titanic_features["Age_Group"] = pd.cut(
    titanic_features["Age"],
    bins=[0, 12, 18, 60, np.inf],
    labels=[
        "Child",
        "Teenager",
        "Adult",
        "Senior"
    ]
)

titanic_features[
    ["Age", "Age_Group"]
].head(10)

    Age Age_Group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5   NaN       NaN
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0  Teenager

## Renaming a Titanic Column

Real-world datasets often contain column names that may not be descriptive enough for a particular project.

For example, `Pclass` represents passenger class.

We can rename it to `Passenger_Class` to make the meaning clearer.

In [106]:
titanic_features = titanic_features.rename(
    columns={
        "Pclass": "Passenger_Class"
    }
)

titanic_features.head()

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Fare_Per_Person,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,3.62500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,35.64165,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,7.92500,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,26.55000,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,8.05000,Adult

# AI / Machine Learning Example
## Titanic Feature Matrix

We can now create a feature matrix using both original and engineered features.

The features will be:

- Passenger Class
- Age
- SibSp
- Parch
- Fare
- Family Size
- Fare Per Person

The target will be `Survived`.

This is only the feature-selection stage.

The Titanic dataset still requires additional preprocessing because it contains missing values and categorical variables.

Those problems will be handled in later sections.

In [ ]:
X_titanic = titanic_features[
    [
        "Passenger_Class",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Family_Size",
        "Fare_Per_Person"
    ]
]

y_titanic = titanic_features["Survived"]

print("Feature Matrix:")
print(X_titanic.head())

print("\nTarget:")
print(y_titanic.head())

print("\nX Shape:", X_titanic.shape)
print("y Shape:", y_titanic.shape)

# Common Mistakes

## Mistake 1: Accidentally Overwriting Original Data

Assigning a transformation back to an existing column replaces its previous values.

If the original column is important, create a new column instead.

## Mistake 2: Dropping Important Columns

Always understand why a column exists before removing it.

A column that appears unnecessary may become useful during Feature Engineering or analysis.

## Mistake 3: Creating Meaningless Features

More features do not automatically mean a better Machine Learning model.

Features should have a logical connection to the problem.

## Mistake 4: Data Leakage

A feature should not contain information that would only be available after the prediction event.

For example, if we are predicting whether a student will pass an exam, using the final result of that exam as an input feature would be data leakage.

## Mistake 5: Division by Zero

When creating ratios, always consider whether the denominator can contain zero.

## Mistake 6: Repeatedly Running Transformation Cells

Google Colab allows cells to be executed multiple times.

Repeated transformations can result in unexpected DataFrame changes.

When experimenting with a dataset, keeping an untouched copy can be useful.

## Mistake 7: Inconsistent Column Naming

Use consistent names such as:

- `Study_Hours`
- `Final_Marks`
- `Family_Size`
- `Fare_Per_Person`

Consistent naming makes Data Science workflows easier to maintain.

# Part 4 — Summary

In this section, we learned how to modify Pandas DataFrames.

### New Concepts

- Creating new columns
- Calculated columns
- Creating features from multiple columns
- Modifying existing columns
- Creating categorical features
- `assign()`
- `rename()`
- `drop()`
- Removing rows
- `insert()`
- Reordering columns

### Data Science

We used Pandas to perform basic Feature Engineering by creating:

- Performance Score
- Performance Level
- Overall Score
- Family Size
- Fare Per Person
- Age Group

### Machine Learning

We created:

- Feature Matrix `X`
- Target Variable `y`

and connected DataFrame transformations to a Machine Learning workflow.

### Workflow So Far

Load Data
↓
Inspect Data
↓
Select & Filter Data
↓
Modify & Transform Data
↓
Feature Engineering
↓
Prepare Data for Cleaning

## Next Topic

# Pandas — Part 5
## Missing Values & Data Cleaning

The next section will introduce new concepts only:

- Detecting missing values
- `isna()`
- `isnull()`
- `notna()`
- Counting missing values
- Missing-value percentages
- `dropna()`
- `fillna()`
- Mean, median and mode imputation
- Forward fill
- Backward fill
- Real-world missing values in Titanic
- Data Science decisions
- AI/ML implications
- Common mistakes

# Pandas — Part 5
## Missing Values & Data Cleaning

Real-world datasets are rarely perfect.

Datasets can contain:

- Missing values
- Incomplete records
- Empty cells
- Incorrect values
- Inconsistent information

Missing values are especially important in Data Science because many Machine Learning algorithms cannot work directly with missing data.

In this section, we will learn how to:

1. Identify missing values
2. Use `isna()`
3. Use `isnull()`
4. Use `notna()`
5. Count missing values
6. Calculate missing-value percentages
7. Identify rows containing missing values
8. Remove missing values using `dropna()`
9. Fill missing values using `fillna()`
10. Fill numerical values using mean
11. Fill numerical values using median
12. Fill categorical values using mode
13. Forward fill
14. Backward fill
15. Handle missing values in the Titanic dataset
16. Understand missing-value decisions in Data Science
17. Understand the Machine Learning impact of missing values
18. Avoid common mistakes

In [108]:
import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E", "F"],
    "Age": [20, np.nan, 22, 21, np.nan, 23],
    "Study_Hours": [4, 6, np.nan, 3, 7, 5],
    "Attendance": [75, 82, 91, np.nan, 88, 79],
    "Marks": [62, 74, 89, 55, np.nan, 71]
}

df = pd.DataFrame(data)

df

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
1       B   NaN          6.0        82.0   74.0
2       C  22.0          NaN        91.0   89.0
3       D  21.0          3.0         NaN   55.0
4       E   NaN          7.0        88.0    NaN
5       F  23.0          5.0        79.0   71.0

## 1. Understanding Missing Values

A missing value means that information is not available for a particular observation.

In Pandas, missing numerical values are commonly represented using `NaN`.

For example:

- A student's age may not have been recorded.
- Attendance may be missing.
- A customer's income may not have been provided.

Before deciding how to handle missing values, we should first identify them.

In [109]:
df.isna()

   Student    Age  Study_Hours  Attendance  Marks
0    False  False        False       False  False
1    False   True        False       False  False
2    False  False         True       False  False
3    False  False        False        True  False
4    False   True        False       False   True
5    False  False        False       False  False

## 2. Using `isnull()`

`isnull()` performs the same basic task as `isna()`.

It returns:

- `True` → Value is missing
- `False` → Value is present

`isna()` and `isnull()` are equivalent in Pandas.

You can use either one.

In [110]:
df.isnull()

   Student    Age  Study_Hours  Attendance  Marks
0    False  False        False       False  False
1    False   True        False       False  False
2    False  False         True       False  False
3    False  False        False        True  False
4    False   True        False       False   True
5    False  False        False       False  False

## 3. Using `notna()`

`notna()` is the opposite of `isna()`.

It returns:

- `True` → Value is present
- `False` → Value is missing

This is useful when we specifically want to identify records containing valid values.

In [111]:
df.notna()

   Student    Age  Study_Hours  Attendance  Marks
0     True   True         True        True   True
1     True  False         True        True   True
2     True   True        False        True   True
3     True   True         True       False   True
4     True  False         True        True  False
5     True   True         True        True   True

## 4. Counting Missing Values

A Boolean DataFrame alone is difficult to interpret.

We can count missing values in each column by combining:

- `isna()`
- `sum()`

Because `True` is treated as `1` and `False` as `0`, summing the result gives the number of missing values.

In [112]:
missing_count = df.isna().sum()

missing_count

Student        0
Age            2
Study_Hours    1
Attendance     1
Marks          1
dtype: int64

## 5. Finding the Total Number of Missing Values

We can calculate the total number of missing cells in the entire DataFrame.

The first `sum()` counts missing values by column.

The second `sum()` adds those column totals together.

In [113]:
total_missing = df.isna().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 5

## 6. Missing-Value Percentage

The number of missing values alone does not always tell us how serious the problem is.

For example:

- 100 missing values in a dataset of 1,000 rows → 10%
- 100 missing values in a dataset of 100,000 rows → 0.1%

Therefore, we can calculate the percentage of missing values in each column.

This helps us decide whether a column should be:

- Filled
- Removed
- Investigated further

In [114]:
missing_percentage = (
    df.isna().mean() * 100
)

missing_percentage

Student         0.000000
Age            33.333333
Study_Hours    16.666667
Attendance     16.666667
Marks          16.666667
dtype: float64

## 7. Displaying Missing-Value Information Together

For Data Cleaning, it is useful to see:

- Number of missing values
- Percentage of missing values

together in one table.

In [115]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": df.isna().mean() * 100
})

missing_summary

             Missing_Count  Missing_Percentage
Student                  0            0.000000
Age                      2           33.333333
Study_Hours              1           16.666667
Attendance               1           16.666667
Marks                    1           16.666667

## 8. Finding Rows with Missing Values

Sometimes we do not want to know only which columns contain missing values.

We want to identify the actual records containing missing information.

We can use `isna().any(axis=1)`.

Here:

`axis=1` means we check across the columns of each row.

A row will be selected if at least one value is missing.

In [116]:
rows_with_missing = df[
    df.isna().any(axis=1)
]

rows_with_missing

  Student   Age  Study_Hours  Attendance  Marks
1       B   NaN          6.0        82.0   74.0
2       C  22.0          NaN        91.0   89.0
3       D  21.0          3.0         NaN   55.0
4       E   NaN          7.0        88.0    NaN

## 9. Finding Rows with No Missing Values

We can also identify complete records.

A complete record contains no missing values in any column.

This can be done using `notna().all(axis=1)`.

In [117]:
complete_rows = df[
    df.notna().all(axis=1)
]

complete_rows

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
5       F  23.0          5.0        79.0   71.0

## 10. Removing Missing Values Using `dropna()`

One approach to missing data is to remove rows containing missing values.

`dropna()` removes rows containing at least one missing value by default.

This method is simple, but it should not be used blindly.

If a dataset contains many missing values, removing rows can result in significant data loss.

In [118]:
df_without_missing = df.dropna()

df_without_missing

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
5       F  23.0          5.0        79.0   71.0

## 11. Dropping Columns with Missing Values

`dropna()` can also be used to remove columns containing missing values.

This can be useful when a column contains an extremely large proportion of missing information.

However, removing a column should only be done after understanding its importance.

In [119]:
df_without_missing_columns = df.dropna(axis=1)

df_without_missing_columns

  Student
0       A
1       B
2       C
3       D
4       E
5       F

## 12. Using `thresh`

Sometimes we do not want to remove every row containing a missing value.

Instead, we can specify the minimum number of non-missing values required.

For example:

`thresh=4`

means that a row must contain at least four non-missing values to remain in the DataFrame.

In [124]:
df_threshold = df.dropna(
    thresh=5
)

df_threshold

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
5       F  23.0          5.0        79.0   71.0

## 13. Filling Missing Values Using `fillna()`

Instead of deleting missing values, we can replace them with another value.

`fillna()` is used for this purpose.

For example, we can replace missing values with `0`.

This is technically easy, but the replacement value should make sense for the variable.

In [125]:
df_zero_filled = df.fillna(0)

df_zero_filled

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
1       B   0.0          6.0        82.0   74.0
2       C  22.0          0.0        91.0   89.0
3       D  21.0          3.0         0.0   55.0
4       E   0.0          7.0        88.0    0.0
5       F  23.0          5.0        79.0   71.0

## 14. Filling Missing Numerical Values with the Mean

The mean is the arithmetic average.

For a numerical column, we can calculate its mean and use that value to replace missing observations.

Mean imputation can be useful when:

- The data is approximately symmetric
- There are no extreme outliers
- The missing proportion is relatively small

However, mean imputation can be affected by outliers.

In [126]:
df_mean = df.copy()

mean_age = df_mean["Age"].mean()

df_mean["Age"] = df_mean["Age"].fillna(mean_age)

df_mean

  Student   Age  Study_Hours  Attendance  Marks
0       A  20.0          4.0        75.0   62.0
1       B  21.5          6.0        82.0   74.0
2       C  22.0          NaN        91.0   89.0
3       D  21.0          3.0         NaN   55.0
4       E  21.5          7.0        88.0    NaN
5       F  23.0          5.0        79.0   71.0

## 15. Filling Missing Values with the Median

The median is the middle value after sorting the data.

Median imputation is often preferred when numerical data contains outliers or is highly skewed.

For example, income data can contain a few extremely high values.

In such situations, the median may represent the typical observation better than the mean.

In [ ]:
df_median = df.copy()

median_age = df_median["Age"].median()

df_median["Age"] = df_median["Age"].fillna(median_age)

df_median

## 16. Mean vs Median

The choice between mean and median depends on the distribution of the data.

### Mean

Useful when the data is reasonably balanced and does not contain severe outliers.

### Median

Often safer when the data is skewed or contains extreme values.

Example:

If salaries are:

- 20,000
- 22,000
- 25,000
- 27,000
- 5,00,000

The extreme value can significantly increase the mean.

The median is less affected by that extreme value.

In [ ]:
salaries = pd.Series([
    20000,
    22000,
    25000,
    27000,
    500000
])

print("Mean:", salaries.mean())
print("Median:", salaries.median())

## 17. Filling Missing Categorical Values with the Mode

The mode is the most frequently occurring value.

Mode imputation is commonly used for categorical columns.

For example, if a column contains:

- Male
- Female
- Female
- Female
- Male
- Missing

we can use the most frequent category to replace the missing value.

The mode can be obtained using `mode()`.

In [127]:
gender_data = pd.Series([
    "Male",
    "Female",
    "Female",
    np.nan,
    "Female",
    "Male"
])

mode_value = gender_data.mode()[0]

gender_filled = gender_data.fillna(mode_value)

gender_filled

0      Male
1    Female
2    Female
3    Female
4    Female
5      Male
dtype: object

## 18. Forward Fill

Forward fill uses the previous available value to fill a missing value.

The method is:

`ffill`

For example, if the values are:

10

20

Missing

40

the missing value will be replaced with 20.

Forward fill is particularly useful for ordered or time-series data where the previous observation can reasonably represent the missing value.

In [128]:
values = pd.Series([
    10,
    20,
    np.nan,
    40,
    np.nan,
    60
])

forward_filled = values.ffill()

forward_filled

0    10.0
1    20.0
2    20.0
3    40.0
4    40.0
5    60.0
dtype: float64

## 19. Backward Fill

Backward fill uses the next available value to fill a missing value.

The method is:

`bfill`

For example, if the values are:

10

Missing

30

the missing value will be replaced with 30.

Backward fill can be useful when the following observation is more appropriate than the previous observation.

In [129]:
values = pd.Series([
    10,
    np.nan,
    30,
    np.nan,
    50
])

backward_filled = values.bfill()

backward_filled

0    10.0
1    30.0
2    30.0
3    50.0
4    50.0
dtype: float64

# Real-World Example
## Missing Values in the Titanic Dataset

The Titanic dataset is a useful example because it contains genuine missing values.

Important columns with missing information include:

- `Age`
- `Cabin`
- `Embarked`

Different columns require different strategies.

For example:

### Age

Age is numerical.

Possible approaches include:

- Mean
- Median
- Model-based imputation

### Embarked

Embarked is categorical.

Mode can be considered when appropriate.

### Cabin

Cabin contains a large amount of missing information.

Instead of blindly filling every missing Cabin value, we should investigate how useful this column is for the problem.

In [130]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## 20. Missing-Value Percentage in Titanic

We can calculate the percentage of missing values for every Titanic column.

This gives us a better understanding of the extent of missing data.

In [131]:
titanic_missing_summary = pd.DataFrame({
    "Missing_Count": titanic.isna().sum(),
    "Missing_Percentage": titanic.isna().mean() * 100
})

titanic_missing_summary.sort_values(
    "Missing_Percentage",
    ascending=False
)

             Missing_Count  Missing_Percentage
Cabin                  687           77.104377
Age                    177           19.865320
Embarked                 2            0.224467
PassengerId              0            0.000000
Name                     0            0.000000
Pclass                   0            0.000000
Survived                 0            0.000000
Sex                      0            0.000000
Parch                    0            0.000000
SibSp                    0            0.000000
Fare                     0            0.000000
Ticket                   0            0.000000

## 21. Filling Titanic Age Using the Median

Age is numerical and contains missing values.

The median is often a reasonable baseline because age distributions can be affected by outliers and are not necessarily perfectly symmetric.

We will create a copy so that the original Titanic DataFrame remains unchanged.

In [132]:
titanic_clean = titanic.copy()

age_median = titanic_clean["Age"].median()

titanic_clean["Age"] = titanic_clean["Age"].fillna(
    age_median
)

print("Missing Age values after filling:")
print(titanic_clean["Age"].isna().sum())

Missing Age values after filling:
0

## 22. Filling Titanic Embarked Using the Mode

`Embarked` is a categorical variable.

For a simple baseline cleaning strategy, we can replace missing values with the most frequent category.

We first calculate the mode and then use it to fill missing values.

In [133]:
embarked_mode = titanic_clean["Embarked"].mode()[0]

titanic_clean["Embarked"] = titanic_clean["Embarked"].fillna(
    embarked_mode
)

print("Missing Embarked values after filling:")
print(titanic_clean["Embarked"].isna().sum())

Missing Embarked values after filling:
0

## 23. Checking the Cleaned Dataset

After performing missing-value treatment, we should always check the result.

We can compare the number of missing values before and after cleaning.

This is an important Data Cleaning habit:

`Clean → Verify → Continue`

In [134]:
print("Missing values before cleaning:")
print(titanic.isna().sum())

print("\nMissing values after cleaning:")
print(titanic_clean.isna().sum())

Missing values before cleaning:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing values after cleaning:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

# AI / Machine Learning Example

Missing values can cause problems during Machine Learning.

Many algorithms cannot directly process `NaN` values.

Therefore, before model training, we generally need to decide how missing values should be handled.

A typical workflow is:

Raw Dataset
↓
Identify Missing Values
↓
Understand Why Values Are Missing
↓
Choose a Strategy
↓
Impute or Remove
↓
Verify
↓
Train Model

The strategy should depend on:

- Data type
- Percentage of missing values
- Distribution of the variable
- Importance of the variable
- Reason for missingness
- Machine Learning algorithm

Missing-value handling is therefore not simply a programming operation. It is a Data Science decision.

In [ ]:
# Example: check whether the selected ML features
# still contain missing values

ml_features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

print(
    titanic_clean[ml_features].isna().sum()
)

# Common Mistakes

## Mistake 1 — Replacing Everything with Zero

Zero may have a completely different meaning from "missing".

For example:

- Age = 0 is not the same as Age = missing
- Salary = 0 is not necessarily the same as Salary = missing

Do not use zero simply because it is convenient.

## Mistake 2 — Always Using the Mean

Mean imputation is not always the best solution.

If a variable contains significant outliers or is heavily skewed, the median may be more appropriate.

## Mistake 3 — Always Dropping Rows

Removing rows can result in significant data loss.

Always check how many observations will be removed before using `dropna()`.

## Mistake 4 — Filling Categorical Data with the Mean

Mean and median are numerical concepts.

For categorical variables, approaches such as mode imputation may be more appropriate.

## Mistake 5 — Ignoring the Reason for Missingness

Missing data can occur for different reasons.

A missing value may mean:

- Information was not collected
- The value was not applicable
- The user chose not to provide it
- A data collection process failed

Understanding the reason can influence the correct treatment.

## Mistake 6 — Data Leakage During Imputation

In Machine Learning, imputation values such as mean or median should generally be calculated using the training data only.

If the entire dataset is used to calculate the value before train/test splitting, information from the test set can leak into the training process.

This will become important when we learn Machine Learning preprocessing pipelines.

## Mistake 7 — Not Verifying the Result

After handling missing values, always check the dataset again.

Never assume that the cleaning operation worked correctly.

# Part 5 — Summary

In this section, we learned how to identify and handle missing values.

### Detection

- `isna()`
- `isnull()`
- `notna()`
- Counting missing values
- Missing-value percentages
- Finding incomplete rows

### Removal

- `dropna()`
- Removing rows
- Removing columns
- Using `thresh`

### Imputation

- `fillna()`
- Mean
- Median
- Mode
- Forward fill
- Backward fill

### Real-World Data

We applied missing-value analysis to the Titanic dataset and handled:

- Missing `Age`
- Missing `Embarked`

We also examined the large number of missing values in `Cabin`.

### Machine Learning Connection

We learned that missing-value treatment is an important preprocessing step before model training.

The general workflow is:

Raw Data
↓
Inspect
↓
Detect Missing Values
↓
Understand Missingness
↓
Choose Strategy
↓
Clean / Impute
↓
Verify
↓
Machine Learning

## Next Topic

# Pandas — Part 6
## Sorting, Ranking & Duplicate Data

We will introduce new concepts only:

- `sort_values()`
- Sorting ascending and descending
- Sorting by multiple columns
- `sort_index()`
- Ranking with `rank()`
- Finding top and bottom records
- Detecting duplicates
- `duplicated()`
- `drop_duplicates()`
- Keeping first/last duplicates
- Real-world Titanic examples
- Data Science use cases
- AI/ML applications
- Common mistakes

# Pandas — Part 6
## Sorting, Ranking & Duplicate Data

After cleaning missing values, the next step is learning how to organize and validate records.

Sorting and duplicate handling are useful for:

- Exploratory Data Analysis (EDA)
- Finding top and bottom records
- Creating rankings
- Identifying repeated observations
- Data Quality Checks
- Preparing datasets for reporting
- Machine Learning preprocessing

In this section, we will learn:

1. `sort_values()`
2. Ascending sorting
3. Descending sorting
4. Sorting by multiple columns
5. Sorting with missing values
6. `sort_index()`
7. `rank()`
8. Finding top records
9. Finding bottom records
10. `duplicated()`
11. Detecting duplicate rows
12. Detecting duplicates using selected columns
13. `drop_duplicates()`
14. Keeping the first duplicate
15. Keeping the last duplicate
16. Removing all duplicated records
17. Duplicate handling on the Titanic dataset
18. Data Science and AI/ML applications
19. Common mistakes

In [139]:
import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Department": [
        "AIML", "CSE", "AIML", "CSE",
        "AIML", "CSE", "AIML", "CSE"
    ],
    "Study_Hours": [5, 8, 6, 3, 9, 7, 4, 10],
    "Attendance": [82, 91, 75, 68, 95, 88, 72, 94],
    "Marks": [74, 92, 81, 55, 96, 87, 63, 98]
}

df = pd.DataFrame(data)

df

  Student Department  Study_Hours  Attendance  Marks
0       A       AIML            5          82     74
1       B        CSE            8          91     92
2       C       AIML            6          75     81
3       D        CSE            3          68     55
4       E       AIML            9          95     96
5       F        CSE            7          88     87
6       G       AIML            4          72     63
7       H        CSE           10          94     98

## 1. `sort_values()`

`sort_values()` is used to arrange rows according to the values in one or more columns.

This is useful when we want to:

- Find the highest marks
- Find students with the lowest attendance
- Arrange customers by revenue
- Sort products by price
- Organize records before analysis

The original DataFrame is not changed unless the result is assigned back to it or modified using the appropriate option.

In [135]:
sorted_df = df.sort_values(
    by="Marks"
)

sorted_df

  Student   Age  Study_Hours  Attendance  Marks
3       D  21.0          3.0         NaN   55.0
0       A  20.0          4.0        75.0   62.0
5       F  23.0          5.0        79.0   71.0
1       B   NaN          6.0        82.0   74.0
2       C  22.0          NaN        91.0   89.0
4       E   NaN          7.0        88.0    NaN

## 2. Ascending Sorting

Ascending order arranges values from smallest to largest.

For example:

55 → 63 → 74 → 81 → 87 → 92 → 96 → 98

Ascending order is the default behavior of `sort_values()`.

It is useful when looking for:

- Lowest scores
- Lowest prices
- Earliest dates
- Smallest values

In [136]:
df.sort_values(
    by="Marks",
    ascending=True
)

  Student   Age  Study_Hours  Attendance  Marks
3       D  21.0          3.0         NaN   55.0
0       A  20.0          4.0        75.0   62.0
5       F  23.0          5.0        79.0   71.0
1       B   NaN          6.0        82.0   74.0
2       C  22.0          NaN        91.0   89.0
4       E   NaN          7.0        88.0    NaN

## 3. Descending Sorting

Descending order arranges values from largest to smallest.

For example:

98 → 96 → 92 → 87 → 81 → 74 → 63 → 55

This is particularly useful when finding:

- Top performers
- Highest sales
- Highest salaries
- Most expensive products
- Largest transactions

In [137]:
df.sort_values(
    by="Marks",
    ascending=False
)

  Student   Age  Study_Hours  Attendance  Marks
2       C  22.0          NaN        91.0   89.0
1       B   NaN          6.0        82.0   74.0
5       F  23.0          5.0        79.0   71.0
0       A  20.0          4.0        75.0   62.0
3       D  21.0          3.0         NaN   55.0
4       E   NaN          7.0        88.0    NaN

## 4. Sorting by Multiple Columns

Sometimes one column is not enough to determine the desired order.

We can sort using multiple columns.

For example:

1. Sort by Department
2. Within each department, sort by Marks in descending order

This is useful when comparing records within groups.

In [140]:
df.sort_values(
    by=["Department", "Marks"],
    ascending=[True, False]
)

  Student Department  Study_Hours  Attendance  Marks
4       E       AIML            9          95     96
2       C       AIML            6          75     81
0       A       AIML            5          82     74
6       G       AIML            4          72     63
7       H        CSE           10          94     98
1       B        CSE            8          91     92
5       F        CSE            7          88     87
3       D        CSE            3          68     55

## 5. Sorting Data Containing Missing Values

Real-world datasets often contain missing values.

Pandas provides the `na_position` parameter to control where missing values appear after sorting.

Two common options are:

- `"first"` → missing values appear first
- `"last"` → missing values appear last

By default, missing values are placed at the end.

In [141]:
df_with_missing = df.copy()

df_with_missing.loc[2, "Marks"] = np.nan
df_with_missing.loc[5, "Marks"] = np.nan

print("Missing values at the end:")
print(
    df_with_missing.sort_values(
        by="Marks",
        na_position="last"
    )
)

print("\nMissing values at the beginning:")
print(
    df_with_missing.sort_values(
        by="Marks",
        na_position="first"
    )
)

Missing values at the end:
  Student Department  Study_Hours  Attendance  Marks
3       D        CSE            3          68   55.0
6       G       AIML            4          72   63.0
0       A       AIML            5          82   74.0
1       B        CSE            8          91   92.0
4       E       AIML            9          95   96.0
7       H        CSE           10          94   98.0
2       C       AIML            6          75    NaN
5       F        CSE            7          88    NaN

Missing values at the beginning:
  Student Department  Study_Hours  Attendance  Marks
2       C       AIML            6          75    NaN
5       F        CSE            7          88    NaN
3       D        CSE            3          68   55.0
6       G       AIML            4          72   63.0
0       A       AIML            5          82   74.0
1       B        CSE            8          91   92.0
4       E       AIML            9          95   96.0
7       H        CSE           10          94   98.0

## 6. `sort_index()`

`sort_index()` sorts the DataFrame according to its index rather than the values of a column.

This is useful when:

- The index order has changed
- We want to restore index ordering
- Working with time-series indexes
- Organizing hierarchical or indexed data

`sort_values()` sorts by column values.

`sort_index()` sorts by index labels.

In [142]:
shuffled_df = df.sample(
    frac=1,
    random_state=42
)

print("Shuffled DataFrame:")
print(shuffled_df)

print("\nSorted by index:")
print(shuffled_df.sort_index())

Shuffled DataFrame:
  Student Department  Study_Hours  Attendance  Marks
1       B        CSE            8          91     92
5       F        CSE            7          88     87
0       A       AIML            5          82     74
7       H        CSE           10          94     98
2       C       AIML            6          75     81
4       E       AIML            9          95     96
3       D        CSE            3          68     55
6       G       AIML            4          72     63

Sorted by index:
  Student Department  Study_Hours  Attendance  Marks
0       A       AIML            5          82     74
1       B        CSE            8          91     92
2       C       AIML            6          75     81
3       D        CSE            3          68     55
4       E       AIML            9          95     96
5       F        CSE            7          88     87
6       G       AIML            4          72     63
7       H        CSE           10          94     98

## 7. Ranking with `rank()`

`rank()` assigns a numerical position to values.

For example, if students have marks:

98
96
92
87

their rankings can be:

1
2
3
4

Ranking is useful for:

- Student rankings
- Sales rankings
- Product rankings
- Competition results
- Performance analysis

By default, ranking starts from the smallest value.

For performance ranking, we usually want the highest value to receive rank 1, so we can use descending order.

In [143]:
df["Marks_Rank"] = df["Marks"].rank(
    ascending=False
)

df

  Student Department  Study_Hours  Attendance  Marks  Marks_Rank
0       A       AIML            5          82     74         6.0
1       B        CSE            8          91     92         3.0
2       C       AIML            6          75     81         5.0
3       D        CSE            3          68     55         8.0
4       E       AIML            9          95     96         2.0
5       F        CSE            7          88     87         4.0
6       G       AIML            4          72     63         7.0
7       H        CSE           10          94     98         1.0

## 8. Handling Ties in Ranking

Two or more records can have the same value.

Pandas provides different ranking methods for handling ties.

Common methods include:

- `average`
- `min`
- `max`
- `first`
- `dense`

The default method is `average`.

The choice depends on how the ranking should behave when multiple observations have the same value.

In [144]:
rank_example = pd.Series([
    95,
    90,
    90,
    85,
    80
])

print("Average ranking:")
print(
    rank_example.rank(
        ascending=False
    )
)

print("\nDense ranking:")
print(
    rank_example.rank(
        ascending=False,
        method="dense"
    )
)

Average ranking:
0    1.0
1    2.5
2    2.5
3    4.0
4    5.0
dtype: float64

Dense ranking:
0    1.0
1    2.0
2    2.0
3    3.0
4    4.0
dtype: float64

## 9. Finding Top and Bottom Records

Pandas provides convenient methods for finding extreme observations.

`nlargest()` returns the rows with the largest values.

`nsmallest()` returns the rows with the smallest values.

These methods are useful when we want:

- Top 5 students
- Bottom 10 products
- Highest revenue transactions
- Lowest-performing records

They can be more convenient than manually sorting the entire DataFrame.

In [145]:
top_3_students = df.nlargest(
    3,
    "Marks"
)

bottom_3_students = df.nsmallest(
    3,
    "Marks"
)

print("Top 3 Students:")
print(top_3_students)

print("\nBottom 3 Students:")
print(bottom_3_students)

Top 3 Students:
  Student Department  Study_Hours  Attendance  Marks  Marks_Rank
7       H        CSE           10          94     98         1.0
4       E       AIML            9          95     96         2.0
1       B        CSE            8          91     92         3.0

Bottom 3 Students:
  Student Department  Study_Hours  Attendance  Marks  Marks_Rank
3       D        CSE            3          68     55         8.0
6       G       AIML            4          72     63         7.0
0       A       AIML            5          82     74         6.0

## 10. Understanding Duplicate Data

A duplicate record occurs when the same information appears more than once.

Duplicates can occur because of:

- Repeated data entry
- Multiple file imports
- Database synchronization problems
- Copy-paste errors
- Combining datasets
- Data collection errors

Duplicate records can distort:

- Counts
- Averages
- Statistics
- Machine Learning models

Therefore, duplicate detection is an important Data Cleaning step.

In [147]:
duplicate_data = {
    "Student_ID": [101, 102, 103, 103, 104, 105, 105],
    "Name": [
        "A", "B", "C", "C",
        "D", "E", "E"
    ],
    "Marks": [
        78, 85, 91, 91,
        67, 88, 88
    ]
}

duplicates_df = pd.DataFrame(
    duplicate_data
)

duplicates_df

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     91
3         103    C     91
4         104    D     67
5         105    E     88
6         105    E     88

## 11. Detecting Duplicate Rows with `duplicated()`

`duplicated()` identifies duplicate rows.

It returns:

- `False` → First occurrence
- `True` → Duplicate occurrence

By default, Pandas considers the first occurrence as the original and subsequent identical rows as duplicates.

In [148]:
duplicates_df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

## 12. Displaying Duplicate Rows

We can use the Boolean result from `duplicated()` to display only duplicate records.

This allows us to inspect the duplicate data before deciding whether it should be removed.

In [150]:
duplicate_rows = duplicates_df[
    duplicates_df.duplicated()
]

duplicate_rows

   Student_ID Name  Marks
3         103    C     91
6         105    E     88

## 13. Detecting Duplicates Using Selected Columns

Sometimes two rows may not be completely identical but may represent the same entity.

For example, if `Student_ID` is supposed to uniquely identify a student, we can check duplicates using only that column.

The `subset` parameter allows us to specify which columns should be considered when identifying duplicates.

In [151]:
duplicates_df[
    duplicates_df.duplicated(
        subset=["Student_ID"]
    )
]

   Student_ID Name  Marks
3         103    C     91
6         105    E     88

## 14. Removing Duplicate Rows

`drop_duplicates()` removes duplicate records.

By default, it keeps the first occurrence and removes later duplicates.

Before removing duplicates from a real dataset, it is good practice to inspect them first.

In [152]:
clean_duplicates = duplicates_df.drop_duplicates()

clean_duplicates

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     91
4         104    D     67
5         105    E     88

## 15. Keeping the Last Duplicate

Sometimes the most recent occurrence should be preserved instead of the first.

`keep="last"` keeps the final occurrence and removes earlier duplicates.

This can be useful when later records contain updated information.

In [153]:
keep_last = duplicates_df.drop_duplicates(
    subset=["Student_ID"],
    keep="last"
)

keep_last

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
3         103    C     91
4         104    D     67
6         105    E     88

## 16. Removing All Records That Have Duplicates

Sometimes we do not want to keep either occurrence.

Using `keep=False` marks every record belonging to a duplicated group for removal.

This is useful when duplicate records are ambiguous and none should be treated as the correct record automatically.

In [154]:
unique_only = duplicates_df.drop_duplicates(
    subset=["Student_ID"],
    keep=False
)

unique_only

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
4         104    D     67

# Real-World Example
## Sorting the Titanic Dataset

We can now apply sorting operations to the Titanic dataset.

For example, we can identify:

- Passengers who paid the highest fares
- Youngest passengers
- Oldest passengers
- Passengers from different classes

In [155]:
# Highest fare passengers

titanic.nlargest(
    10,
    "Fare"
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C

## Sorting Titanic by Age

Sorting by age can help us explore the distribution of passengers.

We can use ascending order to find the youngest passengers first.

In [156]:
titanic.sort_values(
    by="Age",
    ascending=True
).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S

## Sorting Titanic by Passenger Class and Fare

We can sort using multiple columns.

For example:

1. Passenger class in ascending order
2. Fare in descending order

This allows us to see the highest-paying passengers within each class.

In [157]:
titanic.sort_values(
    by=["Pclass", "Fare"],
    ascending=[True, False]
).head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C

## Checking Duplicate Titanic Records

We can check whether the Titanic DataFrame contains completely duplicated rows.

A duplicate check is useful before performing analysis because duplicated observations can affect statistical results.

In [158]:
titanic_duplicate_count = titanic.duplicated().sum()

print(
    "Number of completely duplicated rows:",
    titanic_duplicate_count
)

Number of completely duplicated rows: 0

## Checking Duplicate Passenger IDs

`PassengerId` should uniquely identify each passenger.

Therefore, checking duplicate IDs is a useful data-quality check.

If duplicate IDs exist, we should investigate why before deleting anything.

In [159]:
duplicate_passenger_ids = titanic[
    titanic.duplicated(
        subset=["PassengerId"],
        keep=False
    )
]

duplicate_passenger_ids

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

# Data Science Example
## Finding the Highest-Value Records

Sorting and ranking are frequently used in Data Science to identify important observations.

For example, in a sales dataset we might want to find:

- Top customers
- Highest-value transactions
- Most profitable products
- Lowest-performing products

The same idea applies to the Titanic dataset.

We can identify the passengers who paid the highest fares and then investigate whether other variables show interesting patterns.

In [160]:
top_fare_passengers = titanic.nlargest(
    10,
    "Fare"
)

top_fare_passengers[
    [
        "PassengerId",
        "Name",
        "Pclass",
        "Sex",
        "Age",
        "Fare",
        "Survived"
    ]
]

,PassengerId,Name,Pclass,Sex,Age,Fare,Survived
258,259,"Ward, Miss. Anna",1,female,35.0,512.3292,1
679,680,"Cardeza, Mr. Thomas Drake Martinez",1,male,36.0,512.3292,1
737,738,"Lesurer, Mr. Gustave J",1,male,35.0,512.3292,1
27,28,"Fortune, Mr. Charles Alexander",1,male,19.0,263.0000,0
88,89,"Fortune, Miss. Mabel Helen",1,female,23.0,263.0000,1
341,342,"Fortune, Miss. Alice Elizabeth",1,female,24.0,263.0000,1
438,439,"Fortune, Mr. Mark",1,male,64.0,263.0000,0
311,312,"Ryerson, Miss. Emily Borie",1,female,18.0,262.3750,1
742,743,"Ryerson, Miss. Susan Parker ""Suzette""",1,female,21.0,262.3750,1
118,119,"Baxter, Mr. Quigg Edmond",1,male,24.0,247.5208,0

# AI / Machine Learning Example
## Why Duplicate Data Matters

Duplicate observations can create problems in Machine Learning.

Suppose the same customer appears multiple times in a dataset.

The model may see essentially the same observation repeatedly.

This can:

- Bias the training data
- Distort class distributions
- Affect model evaluation
- Increase the apparent importance of repeated patterns

Duplicate handling is therefore part of Data Quality and Machine Learning preprocessing.

However, not every repeated-looking record is necessarily an error.

Two customers can have the same age, income, and location but still be different people.

Therefore, duplicate detection should be based on the meaning of the dataset and its unique identifiers.

In [ ]:
# Example of checking duplicates before ML preparation

ml_check = titanic.copy()

print(
    "Total rows:",
    len(ml_check)
)

print(
    "Completely duplicated rows:",
    ml_check.duplicated().sum()
)

print(
    "Duplicated Passenger IDs:",
    ml_check["PassengerId"].duplicated().sum()
)

# Common Mistakes

## Mistake 1 — Sorting Without Understanding the Requirement

Ascending and descending order answer different questions.

Always determine whether you need the highest or lowest values.

## Mistake 2 — Assuming the First Duplicate Is Always Wrong

The first occurrence is only the default kept record.

You should determine which record is correct based on the meaning of the dataset.

## Mistake 3 — Removing Duplicates Too Early

Always inspect duplicate records before deleting them.

## Mistake 4 — Using the Wrong Columns for Duplicate Detection

Complete-row duplication is different from duplicate entities.

For example, two rows may differ in one field but still represent the same customer.

Use `subset` when a specific identifier defines uniqueness.

## Mistake 5 — Ignoring Ties in Rankings

If multiple records have the same score, ranking behavior depends on the selected ranking method.

## Mistake 6 — Confusing Index Sorting with Value Sorting

`sort_values()` sorts according to column values.

`sort_index()` sorts according to index labels.

## Mistake 7 — Treating Every Repeated Value as a Duplicate

Repeated values in a column do not necessarily mean duplicate rows.

For example, several students can legitimately have the same marks.

## Mistake 8 — Removing Duplicates Without Domain Knowledge

Data Cleaning decisions should be based on what the data represents.

A repeated transaction may be valid, while a repeated customer record may indicate a data-quality problem.

# Part 6 — Summary

In this section, we learned how to organize and validate Pandas DataFrames.

### Sorting

- `sort_values()`
- Ascending sorting
- Descending sorting
- Sorting by multiple columns
- Sorting missing values
- `sort_index()`

### Ranking

- `rank()`
- Ranking methods
- Handling ties
- `nlargest()`
- `nsmallest()`

### Duplicate Data

- `duplicated()`
- Detecting duplicate rows
- Detecting duplicates using selected columns
- `drop_duplicates()`
- `keep="first"`
- `keep="last"`
- `keep=False`

### Real-World Application

We applied these concepts to the Titanic dataset to:

- Find passengers with the highest fares
- Sort passengers by age
- Sort passengers by class and fare
- Check duplicate records
- Check duplicate Passenger IDs

### Data Science Connection

Sorting and ranking help us explore important observations.

Duplicate detection helps ensure that statistical analysis and Machine Learning are not unintentionally influenced by repeated records.

## Workflow So Far

Load Data
↓
Inspect Data
↓
Select & Filter
↓
Modify & Transform
↓
Handle Missing Values
↓
Sort & Validate
↓
Feature Engineering
↓
Prepare for Analysis / Machine Learning

## Next Topic

# Pandas — Part 7
## GroupBy & Aggregation

We will introduce new concepts only:

- `groupby()`
- Grouping by one column
- Grouping by multiple columns
- `sum()`
- `mean()`
- `median()`
- `min()`
- `max()`
- `count()`
- `size()`
- `agg()`
- Named aggregations
- Group-based analysis
- Titanic analysis
- Data Science use cases
- AI/ML applications
- Common mistakes

# Pandas — Part 7
## GroupBy & Aggregation

In the previous sections, we learned how to inspect, select, filter, modify, clean, sort, and validate data.

Now we will learn how to analyze data **group by group**.

`groupby()` is one of the most important Pandas operations for Data Science.

It allows us to answer questions such as:

- What is the average salary by department?
- What is the average marks by class?
- How many customers belong to each city?
- What is the total revenue by product?
- What is the survival rate by passenger class?
- Which category has the highest average value?

In this section, we will learn:

1. `groupby()`
2. Grouping by one column
3. Grouping by multiple columns
4. `sum()`
5. `mean()`
6. `median()`
7. `min()`
8. `max()`
9. `count()`
10. `size()`
11. `agg()`
12. Named aggregations
13. Group-based filtering and analysis
14. Real-world Titanic analysis
15. Data Science applications
16. AI/ML applications
17. Common mistakes

In [161]:
import numpy as np
import pandas as pd

data = {
    "Student": [
        "A", "B", "C", "D", "E",
        "F", "G", "H", "I", "J"
    ],
    "Department": [
        "AIML", "CSE", "AIML", "CSE", "AIML",
        "CSE", "AIML", "CSE", "AIML", "CSE"
    ],
    "Year": [
        "First", "First", "Second", "Second", "Third",
        "Third", "First", "Second", "Third", "First"
    ],
    "Study_Hours": [
        4, 6, 8, 5, 7,
        9, 3, 6, 8, 7
    ],
    "Attendance": [
        75, 82, 91, 78, 88,
        95, 68, 84, 92, 89
    ],
    "Marks": [
        62, 74, 89, 68, 84,
        96, 55, 79, 91, 86
    ]
}

df = pd.DataFrame(data)

df

  Student Department    Year  Study_Hours  Attendance  Marks
0       A       AIML   First            4          75     62
1       B        CSE   First            6          82     74
2       C       AIML  Second            8          91     89
3       D        CSE  Second            5          78     68
4       E       AIML   Third            7          88     84
5       F        CSE   Third            9          95     96
6       G       AIML   First            3          68     55
7       H        CSE  Second            6          84     79
8       I       AIML   Third            8          92     91
9       J        CSE   First            7          89     86

## 1. Understanding `groupby()`

`groupby()` divides a DataFrame into groups based on the values of one or more columns.

For example, our dataset contains students from:

- AIML
- CSE

We can group all students according to their department.

The important idea is:

```text
DataFrame
    ↓
Group by Department
    ↓
AIML Group
CSE Group
    ↓
Perform Calculation

groupby() is generally used together with aggregation functions such as:

mean()
sum()
min()
max()
count()

In [162]:


department_groups = df.groupby("Department")

department_groups

## 2. Grouping by One Column and Calculating the Mean

One of the most common uses of `groupby()` is calculating averages for each group.

For example, we can calculate the average marks for each department.

This allows us to compare groups instead of looking at individual students.

In [163]:
average_marks = df.groupby("Department")["Marks"].mean()

average_marks

Department
AIML    76.2
CSE     80.6
Name: Marks, dtype: float64

## 3. Grouping by Multiple Columns

We can group data using more than one column.

For example, we can group students by:

- Department
- Year

This creates groups such as:

- AIML + First
- AIML + Second
- AIML + Third
- CSE + First
- CSE + Second
- CSE + Third

This is useful when we want more detailed comparisons.

In [ ]:
department_year_marks = (
    df
    .groupby(["Department", "Year"])["Marks"]
    .mean()
)

department_year_marks

## 4. `sum()`

`sum()` calculates the total value within each group.

For example, we can calculate the total study hours for each department.

This is useful for measuring totals such as:

- Total sales
- Total revenue
- Total study hours
- Total units sold
- Total expenses

In [ ]:
total_study_hours = (
    df
    .groupby("Department")["Study_Hours"]
    .sum()
)

total_study_hours

## 5. `mean()`

`mean()` calculates the arithmetic average within each group.

For example, we can calculate average attendance by department.

Mean is commonly used when comparing the typical value across groups.

In [ ]:
average_attendance = (
    df
    .groupby("Department")["Attendance"]
    .mean()
)

average_attendance

## 6. `median()`

`median()` returns the middle value of each group after sorting the observations.

Median is useful when the data contains outliers or is heavily skewed.

For example, salary data often contains extreme values, so median salary can sometimes be more representative than mean salary.

In [ ]:
median_marks = (
    df
    .groupby("Department")["Marks"]
    .median()
)

median_marks

## 7. `min()` and `max()`

`min()` returns the smallest value in each group.

`max()` returns the largest value in each group.

These operations are useful when we want to understand the range of values within each category.

In [ ]:
minimum_marks = (
    df
    .groupby("Department")["Marks"]
    .min()
)

maximum_marks = (
    df
    .groupby("Department")["Marks"]
    .max()
)

print("Minimum Marks:")
print(minimum_marks)

print("\nMaximum Marks:")
print(maximum_marks)

## 8. `count()`

`count()` counts the number of non-missing values in each group.

This is important because `count()` does not simply count rows.

If a column contains missing values, those missing values are excluded from the count.

This makes `count()` particularly useful when analyzing data completeness.

In [ ]:
marks_count = (
    df
    .groupby("Department")["Marks"]
    .count()
)

marks_count

## 9. `size()`

`size()` counts the total number of rows in each group.

Unlike `count()`, it includes rows even when some values are missing.

The difference is important:

`count()` → Counts non-missing values

`size()` → Counts rows

In [ ]:
group_size = (
    df
    .groupby("Department")
    .size()
)

group_size

## 10. Understanding `count()` vs `size()`

Consider a dataset where one student has a missing marks value.

`count()` will not count that missing Marks value.

`size()` will still count the student because the row exists.

This difference is useful when checking data quality.

In [ ]:
df_with_missing = df.copy()

df_with_missing.loc[2, "Marks"] = np.nan

print("count():")
print(
    df_with_missing
    .groupby("Department")["Marks"]
    .count()
)

print("\nsize():")
print(
    df_with_missing
    .groupby("Department")
    .size()
)

## 11. Using `agg()`

Sometimes we want several statistical calculations at the same time.

For example, instead of calculating mean, minimum, and maximum separately, we can use `agg()`.

This makes grouped analysis more compact and easier to organize.

We can apply multiple aggregation functions to one or more columns.

In [ ]:
department_summary = (
    df
    .groupby("Department")["Marks"]
    .agg([
        "mean",
        "median",
        "min",
        "max"
    ])
)

department_summary

## 12. Aggregating Multiple Columns

`agg()` can also be used when different columns require different calculations.

For example:

- Marks → Mean
- Attendance → Mean
- Study Hours → Sum

This allows us to create a useful summary table in one operation.

In [ ]:
department_summary = (
    df
    .groupby("Department")
    .agg({
        "Marks": "mean",
        "Attendance": "mean",
        "Study_Hours": "sum"
    })
)

department_summary

## 13. Named Aggregations

Named aggregations allow us to control the names of the resulting columns.

Instead of receiving generic names such as `mean`, we can create meaningful names.

For example:

- `Average_Marks`
- `Average_Attendance`
- `Total_Study_Hours`

This makes the resulting DataFrame easier to understand and use in later analysis.

In [ ]:
department_summary = (
    df
    .groupby("Department")
    .agg(
        Average_Marks=("Marks", "mean"),
        Average_Attendance=("Attendance", "mean"),
        Total_Study_Hours=("Study_Hours", "sum"),
        Student_Count=("Student", "count")
    )
)

department_summary

## 14. Using `reset_index()`

After `groupby()`, the grouping column often becomes the index of the resulting DataFrame.

`reset_index()` converts the index back into a regular column.

This is useful when we want the result to behave like a normal DataFrame for further processing, exporting, or visualization.

In [ ]:
department_summary = (
    df
    .groupby("Department")
    .agg(
        Average_Marks=("Marks", "mean"),
        Average_Attendance=("Attendance", "mean"),
        Total_Study_Hours=("Study_Hours", "sum"),
        Student_Count=("Student", "count")
    )
    .reset_index()
)

department_summary

# Real-World Example
## GroupBy with the Titanic Dataset

The Titanic dataset contains categorical variables such as:

- `Pclass`
- `Sex`
- `Embarked`

and numerical variables such as:

- `Age`
- `Fare`
- `Survived`

GroupBy allows us to answer meaningful questions about the dataset.

For example:

- What was the survival rate for each passenger class?
- What was the average fare by passenger class?
- What was the average age by gender?
- How many passengers were in each class?

In [ ]:
titanic.groupby("Pclass")["Survived"].mean()

## 15. Survival Rate by Passenger Class

`Survived` contains:

- `0` → Did not survive
- `1` → Survived

Because the values are binary, calculating their mean gives the proportion of passengers who survived.

For example:

If a group contains:

`1, 1, 0, 0`

the mean is:

`0.50`

which represents a 50% survival rate.

This is a useful Data Science technique for analyzing binary outcomes.

In [ ]:
survival_by_class = (
    titanic
    .groupby("Pclass")["Survived"]
    .mean()
)

survival_by_class

## 16. Grouping by Multiple Columns in Titanic

We can group the Titanic data by more than one categorical variable.

For example:

- Passenger Class
- Sex

This allows us to compare survival rates across combinations of groups.

This type of analysis is useful for identifying patterns and relationships between variables.

In [ ]:
survival_by_class_gender = (
    titanic
    .groupby(["Pclass", "Sex"])["Survived"]
    .mean()
)

survival_by_class_gender

## 17. Multiple Aggregations on Titanic

We can create a summary containing several statistics at once.

For each passenger class, we can calculate:

- Average age
- Average fare
- Survival rate
- Number of passengers

This gives us a compact overview of each passenger class.

In [ ]:
titanic_summary = (
    titanic
    .groupby("Pclass")
    .agg(
        Average_Age=("Age", "mean"),
        Average_Fare=("Fare", "mean"),
        Survival_Rate=("Survived", "mean"),
        Passenger_Count=("PassengerId", "count")
    )
    .reset_index()
)

titanic_summary

# Data Science Example
## Comparing Groups

GroupBy is fundamental to Exploratory Data Analysis.

Suppose we are analyzing a company's employees.

We might group employees by:

- Department
- Location
- Job Role
- Experience Level

Then calculate:

- Average salary
- Median salary
- Employee count
- Maximum salary
- Minimum salary

This allows us to move from individual records to meaningful group-level insights.

The same approach works for:

- Sales data
- Customer data
- Healthcare data
- Education data
- Financial data
- E-commerce data

In [ ]:
employee_data = {
    "Employee": [
        "E1", "E2", "E3", "E4",
        "E5", "E6", "E7", "E8"
    ],
    "Department": [
        "Engineering", "Engineering",
        "Sales", "Sales",
        "HR", "HR",
        "Engineering", "Sales"
    ],
    "Experience": [
        2, 5, 3, 7,
        4, 8, 6, 2
    ],
    "Salary": [
        40000, 75000, 45000, 90000,
        50000, 80000, 85000, 42000
    ]
}

employees = pd.DataFrame(employee_data)

employee_summary = (
    employees
    .groupby("Department")
    .agg(
        Average_Salary=("Salary", "mean"),
        Median_Salary=("Salary", "median"),
        Maximum_Salary=("Salary", "max"),
        Minimum_Salary=("Salary", "min"),
        Average_Experience=("Experience", "mean"),
        Employee_Count=("Employee", "count")
    )
    .reset_index()
)

employee_summary

# AI / Machine Learning Example
## Group-Based Features

Group-level statistics can sometimes be used as Machine Learning features.

For example, in a customer dataset we could calculate:

- Average spending by city
- Average transaction value by customer segment
- Number of purchases per customer
- Average order value per customer

These statistics can then potentially become features.

However, there is an important consideration:

## Data Leakage

If a group statistic is calculated using the target variable or information from the test dataset, information can leak into the model.

For example, when building a predictive model, a target-based group statistic should generally be calculated using training data only and then applied appropriately to validation/test data.

This is why grouped feature engineering must be handled carefully in Machine Learning pipelines.

In [ ]:
# Example of a group-level feature in the student dataset

department_average_marks = (
    df
    .groupby("Department")["Marks"]
    .transform("mean")
)

df["Department_Average_Marks"] = (
    department_average_marks
)

df[
    [
        "Student",
        "Department",
        "Marks",
        "Department_Average_Marks"
    ]
]

## 18. `groupby()` with `transform()`

`agg()` reduces each group to a summary row.

`transform()` calculates a group-level value but returns a result with the same number of rows as the original DataFrame.

This makes `transform()` particularly useful for Feature Engineering.

For example:

Original DataFrame:

10 students

Department average:

AIML → 80

CSE → 75

`transform()` places the appropriate department average beside every student belonging to that department.

This allows the group-level information to become a feature while preserving the original row structure.

In [164]:
df["Department_Average_Attendance"] = (
    df
    .groupby("Department")["Attendance"]
    .transform("mean")
)

df[
    [
        "Student",
        "Department",
        "Attendance",
        "Department_Average_Attendance"
    ]
]

  Student Department  Attendance  Department_Average_Attendance
0       A       AIML          75                           82.8
1       B        CSE          82                           85.6
2       C       AIML          91                           82.8
3       D        CSE          78                           85.6
4       E       AIML          88                           82.8
5       F        CSE          95                           85.6
6       G       AIML          68                           82.8
7       H        CSE          84                           85.6
8       I       AIML          92                           82.8
9       J        CSE          89                           85.6

# Common Mistakes

## Mistake 1 — Confusing `count()` and `size()`

`count()` counts non-missing values.

`size()` counts rows.

They may produce different results when missing values exist.

## Mistake 2 — Forgetting `reset_index()`

After grouping, the grouping column may become the index.

Use `reset_index()` when you need a regular DataFrame structure.

## Mistake 3 — Calculating the Wrong Average

Always understand what the average represents.

An average calculated over the wrong grouping can produce misleading conclusions.

## Mistake 4 — Using `mean()` on Inappropriate Columns

Not every column has a meaningful numerical average.

For example, taking the average of a person's name has no meaningful interpretation.

## Mistake 5 — Ignoring Group Size

A group with an average based on 2 observations should not necessarily be interpreted with the same confidence as a group containing 10,000 observations.

Always consider the number of observations in each group.

## Mistake 6 — Group-Level Data Leakage

When using grouped statistics as Machine Learning features, make sure information from validation or test data does not leak into the training process.

## Mistake 7 — Assuming Correlation or Causation

A difference between groups does not automatically mean one variable caused the difference.

GroupBy helps us discover patterns; further statistical analysis is required to establish stronger conclusions.

# Part 7 — Summary

In this section, we learned how to perform group-based analysis using Pandas.

### Grouping

- `groupby()`
- Grouping by one column
- Grouping by multiple columns

### Aggregation

- `sum()`
- `mean()`
- `median()`
- `min()`
- `max()`
- `count()`
- `size()`
- `agg()`

### Advanced Group Analysis

- Named aggregations
- `reset_index()`
- `transform()`

### Real-World Titanic Analysis

We calculated:

- Survival rate by passenger class
- Survival rate by class and gender
- Average age by class
- Average fare by class
- Passenger counts

### Data Science Connection

`groupby()` is one of the most important tools for Exploratory Data Analysis because it allows us to convert individual observations into meaningful group-level statistics.

### Machine Learning Connection

Group-level statistics can also be transformed into features, but they must be created carefully to prevent data leakage.

## Workflow So Far

Load Data
↓
Inspect Data
↓
Select & Filter
↓
Modify & Transform
↓
Handle Missing Values
↓
Sort & Validate
↓
Group & Aggregate
↓
Feature Engineering
↓
Prepare for Machine Learning

## Next Topic

# Pandas — Part 8
## Combining DataFrames

We will introduce new concepts only:

- `concat()`
- Row-wise concatenation
- Column-wise concatenation
- `merge()`
- Inner join
- Left join
- Right join
- Outer join
- Joining using multiple columns
- `join()`
- Real-world multi-table examples
- Data Science applications
- AI/ML applications
- Common mistakes

# Pandas — Part 8
## Combining DataFrames

Real-world data is often distributed across multiple tables or files.

For example, an e-commerce company may have separate datasets for:

- Customers
- Orders
- Products
- Payments

Similarly, a college may have separate datasets for:

- Students
- Attendance
- Marks
- Courses

Pandas provides several operations for combining these datasets.

In this section, we will learn:

1. `concat()`
2. Row-wise concatenation
3. Column-wise concatenation
4. `merge()`
5. Inner join
6. Left join
7. Right join
8. Outer join
9. Merging using multiple columns
10. `join()`
11. Combining real-world Titanic-related data
12. Data Science applications
13. AI/ML applications
14. Common mistakes

The important distinction is:

`concat()` → Combine DataFrames by stacking them

`merge()` → Combine DataFrames using related columns

`join()` → Combine DataFrames primarily using indexes

In [166]:
import numpy as np
import pandas as pd

students_1 = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["A", "B", "C"],
    "Marks": [78, 85, 92]
})

students_2 = pd.DataFrame({
    "Student_ID": [104, 105, 106],
    "Name": ["D", "E", "F"],
    "Marks": [67, 88, 74]
})

print("Students 1:")
print(students_1)

print("\nStudents 2:")
print(students_2)

Students 1:
   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     92

Students 2:
   Student_ID Name  Marks
0         104    D     67
1         105    E     88
2         106    F     74

## 1. `concat()`

`concat()` is used to concatenate multiple Pandas objects.

It is commonly used when datasets have the same structure and need to be combined.

For example, suppose:

- `students_1` contains students 101–103
- `students_2` contains students 104–106

Both DataFrames contain the same columns.

We can combine them row by row.

This is called **row-wise concatenation**.

In [167]:
combined_students = pd.concat(
    [students_1, students_2]
)

combined_students

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     92
0         104    D     67
1         105    E     88
2         106    F     74

## 2. Resetting the Index After Concatenation

When DataFrames are concatenated, Pandas preserves the original indexes.

This can result in repeated index values.

If we want a fresh sequential index, we can use:

`ignore_index=True`

This is commonly useful when combining datasets from multiple files.

In [168]:
combined_students = pd.concat(
    [students_1, students_2],
    ignore_index=True
)

combined_students

   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     92
3         104    D     67
4         105    E     88
5         106    F     74

## 3. Column-Wise Concatenation

`concat()` can also combine DataFrames horizontally.

This means the columns are placed next to each other.

This is useful when two DataFrames:

- Have the same number of rows
- Represent different features
- Need to be combined side by side

For example, one DataFrame may contain student information while another contains academic information.

In [169]:
student_info = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["A", "B", "C"]
})

academic_info = pd.DataFrame({
    "Study_Hours": [5, 7, 8],
    "Attendance": [80, 90, 85]
})

combined_columns = pd.concat(
    [student_info, academic_info],
    axis=1
)

combined_columns

   Student_ID Name  Study_Hours  Attendance
0         101    A            5          80
1         102    B            7          90
2         103    C            8          85

## 4. Understanding `axis`

The `axis` parameter determines the direction of concatenation.

`axis=0`

Means rows are combined vertically.

`axis=1`

Means columns are combined horizontally.

Therefore:

`axis=0` → Add more rows

`axis=1` → Add more columns

In [170]:
vertical = pd.concat(
    [students_1, students_2],
    axis=0,
    ignore_index=True
)

horizontal = pd.concat(
    [student_info, academic_info],
    axis=1
)

print("Vertical:")
print(vertical)

print("\nHorizontal:")
print(horizontal)

Vertical:
   Student_ID Name  Marks
0         101    A     78
1         102    B     85
2         103    C     92
3         104    D     67
4         105    E     88
5         106    F     74

Horizontal:
   Student_ID Name  Study_Hours  Attendance
0         101    A            5          80
1         102    B            7          90
2         103    C            8          85

## 5. Concatenating DataFrames with Different Columns

Real-world datasets may not always contain exactly the same columns.

When DataFrames with different columns are concatenated, Pandas creates the union of all columns.

Values that do not exist in a particular DataFrame become missing values.

This is important because combining datasets can introduce new missing values.

In [171]:
batch_1 = pd.DataFrame({
    "Student_ID": [101, 102],
    "Name": ["A", "B"],
    "Marks": [80, 90]
})

batch_2 = pd.DataFrame({
    "Student_ID": [103, 104],
    "Name": ["C", "D"],
    "Attendance": [85, 92]
})

different_columns = pd.concat(
    [batch_1, batch_2],
    ignore_index=True
)

different_columns

   Student_ID Name  Marks  Attendance
0         101    A   80.0         NaN
1         102    B   90.0         NaN
2         103    C    NaN        85.0
3         104    D    NaN        92.0

# `merge()`

`merge()` is used when two DataFrames contain related information that should be combined using one or more common columns.

For example:

Students:

`Student_ID | Name`

Marks:

`Student_ID | Marks`

Both tables contain `Student_ID`.

We can use that common column to combine the information.

This is similar to SQL joins.

In [172]:
student_details = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["A", "B", "C", "D"],
    "Department": ["AIML", "CSE", "AIML", "ECE"]
})

student_marks = pd.DataFrame({
    "Student_ID": [101, 102, 103, 105],
    "Marks": [78, 85, 92, 88]
})

print("Student Details:")
print(student_details)

print("\nStudent Marks:")
print(student_marks)

Student Details:
   Student_ID Name Department
0         101    A       AIML
1         102    B        CSE
2         103    C       AIML
3         104    D        ECE

Student Marks:
   Student_ID  Marks
0         101     78
1         102     85
2         103     92
3         105     88

## 6. Inner Join

An inner join keeps only records that have matching keys in both DataFrames.

In this example:

Student IDs in the first DataFrame:

101, 102, 103, 104

Student IDs in the second DataFrame:

101, 102, 103, 105

The common IDs are:

101, 102, 103

Therefore, an inner join keeps only these three students.

Inner joins are useful when we only want records that exist in both datasets.

In [173]:
inner_merged = pd.merge(
    student_details,
    student_marks,
    on="Student_ID",
    how="inner"
)

inner_merged

   Student_ID Name Department  Marks
0         101    A       AIML     78
1         102    B        CSE     85
2         103    C       AIML     92

## 7. Left Join

A left join keeps every record from the left DataFrame.

Matching information from the right DataFrame is added when available.

If there is no matching record, Pandas inserts a missing value.

In this example, Student ID 104 exists in the student details table but not in the marks table.

Therefore, Student 104 remains in the result but has a missing Marks value.

In [174]:
left_merged = pd.merge(
    student_details,
    student_marks,
    on="Student_ID",
    how="left"
)

left_merged

   Student_ID Name Department  Marks
0         101    A       AIML   78.0
1         102    B        CSE   85.0
2         103    C       AIML   92.0
3         104    D        ECE    NaN

## 8. Right Join

A right join keeps every record from the right DataFrame.

Matching information from the left DataFrame is added when available.

In this example, Student ID 105 exists in the marks table but not in the student details table.

Therefore, Student 105 remains in the result with missing information from the left DataFrame.

In [175]:
right_merged = pd.merge(
    student_details,
    student_marks,
    on="Student_ID",
    how="right"
)

right_merged

   Student_ID Name Department  Marks
0         101    A       AIML     78
1         102    B        CSE     85
2         103    C       AIML     92
3         105  NaN        NaN     88

## 9. Outer Join

An outer join keeps all records from both DataFrames.

If a matching record does not exist, Pandas inserts a missing value.

In this example:

- Student 104 exists only in the first table.
- Student 105 exists only in the second table.

Both students will remain in the final result.

Outer joins are useful when we want to preserve all information from both datasets.

In [176]:
outer_merged = pd.merge(
    student_details,
    student_marks,
    on="Student_ID",
    how="outer"
)

outer_merged

   Student_ID Name Department  Marks
0         101    A       AIML   78.0
1         102    B        CSE   85.0
2         103    C       AIML   92.0
3         104    D        ECE    NaN
4         105  NaN        NaN   88.0

## 10. Understanding Join Types

The four major join types are:

### Inner

Keep matching records only.

### Left

Keep everything from the left DataFrame.

### Right

Keep everything from the right DataFrame.

### Outer

Keep everything from both DataFrames.

A useful way to remember them:

`inner` → Intersection

`left` → Everything on left

`right` → Everything on right

`outer` → Union

In [177]:
join_types = {
    "inner": pd.merge(
        student_details,
        student_marks,
        on="Student_ID",
        how="inner"
    ),
    "left": pd.merge(
        student_details,
        student_marks,
        on="Student_ID",
        how="left"
    ),
    "right": pd.merge(
        student_details,
        student_marks,
        on="Student_ID",
        how="right"
    ),
    "outer": pd.merge(
        student_details,
        student_marks,
        on="Student_ID",
        how="outer"
    )
}

for name, result in join_types.items():
    print(f"\n{name.upper()} JOIN")
    print(result)

INNER JOIN
   Student_ID Name Department  Marks
0         101    A       AIML     78
1         102    B        CSE     85
2         103    C       AIML     92

LEFT JOIN
   Student_ID Name Department  Marks
0         101    A       AIML   78.0
1         102    B        CSE   85.0
2         103    C       AIML   92.0
3         104    D        ECE    NaN

RIGHT JOIN
   Student_ID Name Department  Marks
0         101    A       AIML     78
1         102    B        CSE     85
2         103    C       AIML     92
3         105  NaN        NaN     88

OUTER JOIN
   Student_ID Name Department  Marks
0         101    A       AIML   78.0
1         102    B        CSE   85.0
2         103    C       AIML   92.0
3         104    D        ECE    NaN
4         105  NaN        NaN   88.0

## 11. Merging Using Different Column Names

Sometimes the key columns represent the same information but have different names.

For example:

First DataFrame:

`Student_ID`

Second DataFrame:

`ID`

We can specify:

- `left_on`
- `right_on`

to tell Pandas which columns should be matched.

In [178]:
students = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["A", "B", "C"]
})

marks = pd.DataFrame({
    "ID": [101, 102, 103],
    "Marks": [78, 85, 92]
})

merged_different_names = pd.merge(
    students,
    marks,
    left_on="Student_ID",
    right_on="ID",
    how="inner"
)

merged_different_names

   Student_ID Name   ID  Marks
0         101    A  101     78
1         102    B  102     85
2         103    C  103     92

## 12. Merging Using Multiple Columns

Sometimes a single column is not enough to uniquely identify a record.

For example, suppose an academic dataset contains:

- Student_ID
- Semester

Another dataset also contains:

- Student_ID
- Semester

We can merge using both columns.

This creates a composite key.

Multiple-column merging is common in real-world relational datasets.

In [179]:
student_semester = pd.DataFrame({
    "Student_ID": [101, 101, 102, 102],
    "Semester": [1, 2, 1, 2],
    "Attendance": [85, 88, 90, 92]
})

student_marks_semester = pd.DataFrame({
    "Student_ID": [101, 101, 102, 102],
    "Semester": [1, 2, 1, 2],
    "Marks": [78, 82, 85, 91]
})

semester_merged = pd.merge(
    student_semester,
    student_marks_semester,
    on=["Student_ID", "Semester"],
    how="inner"
)

semester_merged

   Student_ID  Semester  Attendance  Marks
0         101         1          85     78
1         101         2          88     82
2         102         1          90     85
3         102         2          92     91

# `join()`

## 13. Using `join()`

`join()` is another method for combining DataFrames.

It is particularly convenient when the related information is stored using indexes.

For example:

DataFrame 1:

`Student_ID` as index

DataFrame 2:

`Student_ID` as index

We can join the two DataFrames using their indexes.

A common distinction is:

`merge()` → Usually combines using columns

`join()` → Convenient for combining using indexes

In [180]:
student_info_indexed = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Department": ["AIML", "CSE", "AIML"]
}, index=[101, 102, 103])

student_marks_indexed = pd.DataFrame({
    "Marks": [78, 85, 92],
    "Attendance": [85, 90, 88]
}, index=[101, 102, 103])

joined_data = student_info_indexed.join(
    student_marks_indexed
)

joined_data

    Name Department  Marks  Attendance
101    A       AIML     78          85
102    B        CSE     85          90
103    C       AIML     92          88

# Real-World Example
## Combining Titanic-Related Data

The Titanic dataset itself is generally available as one main table, but real Data Science projects often involve multiple related tables.

To understand this workflow, we can create a separate passenger-details table and a separate passenger-ticket table from the Titanic dataset.

Both tables will share `PassengerId`.

We can then merge them back together.

This simulates a common real-world situation:

`Passenger Table`
+
`Ticket Table`
↓
`Combined Dataset`

The important concept is that real-world data often needs to be integrated before analysis or Machine Learning.

In [ ]:
passenger_details = titanic[
    [
        "PassengerId",
        "Name",
        "Sex",
        "Age",
        "Pclass"
    ]
].copy()

ticket_details = titanic[
    [
        "PassengerId",
        "Fare",
        "Cabin",
        "Embarked"
    ]
].copy()

print("Passenger Details:")
print(passenger_details.head())

print("\nTicket Details:")
print(ticket_details.head())

## 14. Merging Titanic Tables

We can merge the two simulated tables using `PassengerId`.

Since both tables originate from the same Titanic dataset, an inner join should retain passengers whose IDs are present in both tables.

In [ ]:
titanic_combined = pd.merge(
    passenger_details,
    ticket_details,
    on="PassengerId",
    how="inner"
)

titanic_combined.head()

## 15. Data Science Example

Combining DataFrames is extremely important in real-world analytics.

Imagine an e-commerce company has:

`customers.csv`

containing:

- Customer ID
- Name
- City

and:

`orders.csv`

containing:

- Order ID
- Customer ID
- Product
- Amount

The two datasets can be connected using Customer ID.

After merging, we can answer questions such as:

- Which city generates the most revenue?
- Which customers spend the most?
- What products are popular in each city?
- How many orders does each customer make?

This is one of the foundations of relational data analysis.

In [ ]:
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Customer_Name": [
        "Rahul",
        "Priya",
        "Amit",
        "Neha"
    ],
    "City": [
        "Mumbai",
        "Pune",
        "Nashik",
        "Mumbai"
    ]
})

orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005],
    "Customer_ID": [1, 2, 1, 3, 4],
    "Amount": [1200, 800, 2500, 950, 1800]
})

customer_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="inner"
)

customer_orders

## 16. AI / Machine Learning Example

Combining multiple datasets is often required before Machine Learning.

For example, suppose we are building a customer churn model.

We may have separate datasets containing:

`Customer Information`

- Age
- Gender
- City

`Transaction Information`

- Number of orders
- Total spending
- Average order value

`Support Information`

- Number of complaints
- Support calls

These datasets can be merged using a common customer identifier.

The final dataset can then be transformed into:

`X` → Feature Matrix

`y` → Target

An important concern is **data leakage**.

When joining datasets, we must ensure that information from the future or from the target period is not accidentally included in the training features.

In [ ]:
customer_features = (
    customer_orders
    .groupby("Customer_ID")
    .agg(
        Total_Spending=("Amount", "sum"),
        Number_of_Orders=("Order_ID", "count"),
        Average_Order_Value=("Amount", "mean")
    )
    .reset_index()
)

customer_model_data = pd.merge(
    customers,
    customer_features,
    on="Customer_ID",
    how="left"
)

customer_model_data

# Common Mistakes

## Mistake 1 — Using `concat()` When a `merge()` Is Required

Use `concat()` when datasets need to be stacked.

Use `merge()` when datasets need to be connected using a key.

## Mistake 2 — Choosing the Wrong Join Type

An inner join can remove records that do not have a match.

A left join preserves all records from the left DataFrame.

Always understand which records you need to preserve.

## Mistake 3 — Joining on the Wrong Column

The join key must represent the same entity in both datasets.

For example, joining customers using their names can be dangerous because names may not be unique.

A unique identifier such as Customer ID is usually safer.

## Mistake 4 — Unexpected Row Multiplication

If the join key appears multiple times in both DataFrames, a merge can create multiple combinations.

This can unexpectedly increase the number of rows.

Always check the uniqueness of your join keys.

## Mistake 5 — Ignoring Missing Values After a Join

Left, right, and outer joins can introduce missing values when matching records do not exist.

The resulting DataFrame should be checked after merging.

## Mistake 6 — Duplicate Columns

If both DataFrames contain columns with the same name, Pandas may add suffixes such as `_x` and `_y`.

These columns should be reviewed carefully.

## Mistake 7 — Data Leakage

When combining datasets for Machine Learning, do not accidentally merge information that would not have been available at prediction time.

## Mistake 8 — Not Checking the Result

After combining datasets, always inspect:

- Number of rows
- Number of columns
- Missing values
- Duplicate records
- Join keys
- Unexpected values

# Part 8 — Summary

In this section, we learned how to combine multiple Pandas DataFrames.

### `concat()`

- Row-wise concatenation
- Column-wise concatenation
- `axis=0`
- `axis=1`
- `ignore_index`

### `merge()`

- Inner join
- Left join
- Right join
- Outer join
- Different key names
- Multiple-column joins

### `join()`

- Joining using indexes
- Combining indexed DataFrames

### Real-World Application

We simulated a multi-table Titanic workflow and combined:

- Passenger information
- Ticket information

using `PassengerId`.

We also created a customer-order example to demonstrate how multiple business datasets can be integrated.

### Machine Learning Connection

Combining datasets is often an important preprocessing step before creating the final feature matrix.

However, joins must be performed carefully to avoid:

- Incorrect records
- Row multiplication
- Missing information
- Duplicate information
- Data leakage

````markdown
# Pandas — 25 Coding Practice Questions

> Use Pandas for all questions. NumPy may be used where required for data generation or calculations.
>
> Do not use external Machine Learning libraries unless explicitly required.

---

## Q1. Create a DataFrame

Create a Pandas DataFrame containing the following student information:

- Student_ID
- Name
- Age
- Department
- Marks

Create records for at least 8 students.

Display the DataFrame.

---

## Q2. Inspect a DataFrame

Using the DataFrame from Q1:

1. Display the first 5 rows.
2. Display the last 3 rows.
3. Display the shape.
4. Display the column names.
5. Display the data types.
6. Display basic statistical information.

---

## Q3. Single and Multiple Column Selection

Using the student DataFrame:

1. Select only the `Name` column.
2. Select only the `Marks` column.
3. Select `Name`, `Department`, and `Marks`.
4. Display the resulting DataFrames.

---

## Q4. `loc[]` and `iloc[]`

Using the student DataFrame:

1. Select the first 5 rows using `iloc[]`.
2. Select the first 3 rows and first 3 columns using `iloc[]`.
3. Select the `Name` and `Marks` columns for the first 5 students using `loc[]`.
4. Select the rows where the index is between 2 and 5 using `loc[]`.

---

## Q5. Boolean Filtering

Using the student DataFrame:

1. Find students with marks greater than 75.
2. Find students with attendance greater than 80.
3. Find students whose study hours are greater than 5.
4. Find students whose marks are below 40.

---

## Q6. Multiple Conditions

Using the student DataFrame:

1. Find students with marks greater than 70 AND attendance greater than 80.
2. Find students with marks greater than 85 OR study hours greater than 7.
3. Find students from the `AIML` department AND marks greater than 70.

---

## Q7. `isin()` and `between()`

Using the student DataFrame:

1. Find students belonging to either `AIML` or `CSE`.
2. Find students whose marks are between 60 and 80.
3. Find students whose attendance is between 70 and 90.
4. Find students whose age is between 20 and 22.

---

## Q8. Create New Columns

Using the student DataFrame:

1. Create `Study_Minutes` from `Study_Hours`.
2. Create `Passed` where:
   - Marks >= 40 → 1
   - Marks < 40 → 0
3. Create `Marks_Percentage` from marks.
4. Display the updated DataFrame.

---

## Q9. Feature Engineering

Create a new column called `Performance_Score` using:

```text
Performance_Score =
Marks × 0.7 + Attendance × 0.3
````

Then create:

```text
Performance_Level
```

using:

* Marks >= 80 → Excellent
* Marks >= 60 → Good
* Marks >= 40 → Average
* Marks < 40 → Needs Improvement

---

## Q10. Rename and Drop Columns

Using the student DataFrame:

1. Rename `Marks` to `Final_Marks`.
2. Rename `Study_Hours` to `Daily_Study_Hours`.
3. Remove the `Age` column.
4. Display the updated DataFrame.

---

## Q11. Sorting

Using the student DataFrame:

1. Sort students by marks in ascending order.
2. Sort students by marks in descending order.
3. Sort students by attendance in descending order.
4. Sort by department first and marks second.
5. Within each department, arrange students from highest to lowest marks.

---

## Q12. Ranking

Using the student DataFrame:

1. Create a `Rank` column based on marks.
2. Make the student with the highest marks Rank 1.
3. Display the top 5 students based on rank.

---

## Q13. Find Top and Bottom Students

Using Pandas:

1. Find the top 3 students based on marks.
2. Find the bottom 3 students based on marks.
3. Find the top 5 students based on attendance.
4. Find the student with the highest study hours.

Use `nlargest()` and `nsmallest()`.

---

## Q14. Missing Values

Create a DataFrame containing:

* Student
* Age
* Marks
* Attendance
* Study_Hours

Intentionally introduce missing values.

Then:

1. Detect missing values.
2. Count missing values per column.
3. Calculate missing-value percentages.
4. Display rows containing at least one missing value.
5. Display rows containing no missing values.

---

## Q15. Handle Missing Values

Using the DataFrame from Q14:

1. Fill missing `Age` values using the median.
2. Fill missing `Marks` using the mean.
3. Fill missing `Attendance` using the median.
4. Remove rows that still contain missing values.
5. Verify that no missing values remain.

---

## Q16. Duplicate Data

Create a DataFrame containing duplicate student records.

Then:

1. Detect duplicate rows using `duplicated()`.
2. Display only duplicate rows.
3. Count the number of duplicates.
4. Remove duplicates using `drop_duplicates()`.
5. Check the DataFrame again.

---

## Q17. Duplicate IDs

Create a DataFrame containing:

* Student_ID
* Name
* Department
* Marks

Include repeated `Student_ID` values.

Then:

1. Find duplicated Student IDs.
2. Display all records having duplicated IDs.
3. Keep only the first occurrence.
4. Keep only the last occurrence.
5. Remove all records belonging to duplicated IDs.

---

## Q18. GroupBy — Student Analysis

Create a student DataFrame containing:

* Student_ID
* Department
* Study_Hours
* Attendance
* Marks

Using `groupby()`:

1. Calculate average marks by department.
2. Calculate average attendance by department.
3. Calculate total study hours by department.
4. Find minimum marks by department.
5. Find maximum marks by department.
6. Count students in each department.

---

## Q19. GroupBy with Multiple Columns

Using the same dataset:

Group the data by:

```text
Department
Year
```

Calculate:

1. Average marks.
2. Average attendance.
3. Maximum marks.
4. Minimum marks.
5. Number of students.

Reset the index of the resulting DataFrame.

---

## Q20. Aggregation Using `agg()`

Using a student DataFrame, create a department-level summary containing:

```text
Average_Marks
Median_Marks
Maximum_Marks
Minimum_Marks
Average_Attendance
Total_Study_Hours
Student_Count
```

Use `groupby()` and `agg()`.

Use named aggregations so the resulting column names are meaningful.

---

## Q21. `transform()` Feature Engineering

Using the student dataset:

1. Calculate the average marks of each department.
2. Add the department average marks back to every student as:
   `Department_Average_Marks`
3. Calculate the difference between each student's marks and their department average.
4. Store the result as:
   `Difference_From_Department_Average`

---

## Q22. Combining DataFrames

Create three separate DataFrames:

### Student Information

```text
Student_ID
Name
Department
```

### Academic Information

```text
Student_ID
Marks
Attendance
```

### Course Information

```text
Student_ID
Course
```

Then:

1. Combine student and academic information using `merge()`.
2. Merge the course information into the resulting DataFrame.
3. Use `Student_ID` as the common key.
4. Display the final DataFrame.

---

## Q23. Join Types

Create two DataFrames containing student information with some overlapping and some non-overlapping Student IDs.

Perform:

1. Inner join.
2. Left join.
3. Right join.
4. Outer join.

For each result:

1. Display the DataFrame.
2. Count the number of rows.
3. Identify which records contain missing values.

---

## Q24. Real-Life Titanic Analysis

Using the Titanic dataset:

1. Load the dataset into Pandas.
2. Display its shape.
3. Check missing values.
4. Calculate missing-value percentages.
5. Find the top 10 passengers based on fare.
6. Calculate survival rate by passenger class.
7. Calculate survival rate by gender.
8. Calculate survival rate by passenger class and gender.
9. Calculate average fare by passenger class.
10. Calculate average age by passenger class.
11. Create `Family_Size` using:
    `SibSp + Parch + 1`
12. Create `Fare_Per_Person`.
13. Create an `Age_Group` column.
14. Sort passengers by fare.
15. Check for duplicate rows.

---

## Q25. Complete Pandas Data Science Challenge

Create a synthetic dataset containing at least 100 students with:

```text
Student_ID
Name
Age
Department
Year
Study_Hours
Attendance
Previous_Score
Final_Score
```

Then perform the following complete analysis.

### Data Inspection

1. Display the first 5 rows.
2. Display the last 5 rows.
3. Display the shape.
4. Display column names.
5. Display data types.
6. Generate descriptive statistics.

### Data Cleaning

7. Introduce some missing values.
8. Detect missing values.
9. Calculate missing-value percentages.
10. Fill appropriate numerical missing values.
11. Check for duplicate rows.
12. Remove duplicate records.

### Feature Engineering

13. Create `Study_Minutes`.
14. Create `Performance_Score` using:

```text
Final_Score × 0.7 + Attendance × 0.3
```

15. Create `Performance_Level`:

```text
80+  → Excellent
60–79 → Good
40–59 → Average
<40 → Needs Improvement
```

16. Create `Passed`:

```text
Final_Score >= 40 → 1
Final_Score < 40 → 0
```

17. Create `Department_Average`.
18. Create `Difference_From_Department_Average`.

### Analysis

19. Find the top 10 students based on Final Score.
20. Find the bottom 10 students.
21. Calculate average Final Score by department.
22. Calculate average Attendance by department.
23. Calculate student count by department.
24. Find the department with the highest average Final Score.

### Machine Learning Preparation

25. Create:

```text
X =
Study_Hours
Attendance
Previous_Score
Performance_Score
Department_Average
```

Create:

```text
y = Passed
```

Finally:

1. Display `X.head()`.
2. Display `y.head()`.
3. Display `X.shape`.
4. Display `y.shape`.
5. Verify that `X` contains no missing values.
6. Verify that `y` contains no missing values.

---

# End of Pandas Practice Set

These 25 questions cover:

* DataFrame creation
* Inspection
* Selection
* Filtering
* `loc[]`
* `iloc[]`
* `isin()`
* `between()`
* Column creation
* Feature Engineering
* Renaming
* Dropping
* Sorting
* Ranking
* Missing values
* Duplicate handling
* `groupby()`
* Aggregation
* `agg()`
* `transform()`
* `concat()`
* `merge()`
* Joins
* Titanic analysis
* Machine Learning preparation

```
```

# Pandas — 25 Practice Questions: Solutions

Below, each solution follows the same course format:

**Markdown / Explanation → Code**

---

## Q1. Create a DataFrame

### Markdown Cell

```markdown
## Solution — Q1

Create a dictionary where each key represents a column and each value
contains the data for that column.

The dictionary can then be converted into a Pandas DataFrame using
`pd.DataFrame()`.
```

### Code Cell

```python
import pandas as pd
import numpy as np

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Age": [20, 21, 19, 22, 20, 23, 21, 22],
    "Department": [
        "AIML", "CSE", "AIML", "ECE",
        "CSE", "AIML", "ECE", "CSE"
    ],
    "Marks": [78, 85, 92, 67, 74, 89, 55, 81]
}

df = pd.DataFrame(data)

df
```

---

# Q2. Inspect a DataFrame

### Markdown Cell

```markdown
## Solution — Q2

Pandas provides several methods for inspecting a DataFrame.

`head()` displays the first rows.

`tail()` displays the last rows.

`shape` returns the number of rows and columns.

`columns` returns the column names.

`dtypes` displays the data type of each column.

`describe()` provides statistical information about numerical columns.
```

### Code Cell

```python
print("First 5 rows:")
print(df.head())

print("\nLast 3 rows:")
print(df.tail(3))

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nStatistical Summary:")
print(df.describe())
```

---

# Q3. Single and Multiple Column Selection

### Markdown Cell

```markdown
## Solution — Q3

A single column can be selected using its column name.

Multiple columns can be selected by passing a list of column names.

The result of single-column selection is generally a Series,
while multiple-column selection returns a DataFrame.
```

### Code Cell

```python
name_column = df["Name"]

marks_column = df["Marks"]

selected_columns = df[
    ["Name", "Department", "Marks"]
]

print("Name:")
print(name_column)

print("\nMarks:")
print(marks_column)

print("\nMultiple Columns:")
print(selected_columns)
```

---

# Q4. `loc[]` and `iloc[]`

### Markdown Cell

```markdown
## Solution — Q4

`iloc[]` uses integer positions.

`loc[]` uses labels such as index values and column names.

For example:

`iloc[0:5]` selects the first five rows based on position.

`loc[2:5]` selects rows whose index labels range from 2 to 5.
```

### Code Cell

```python
print("First 5 rows using iloc:")
print(df.iloc[:5])

print("\nFirst 3 rows and first 3 columns:")
print(df.iloc[:3, :3])

print("\nName and Marks using loc:")
print(
    df.loc[:4, ["Name", "Marks"]]
)

print("\nRows with index 2 to 5:")
print(
    df.loc[2:5]
)
```

---

# Q5. Boolean Filtering

### Markdown Cell

```markdown
## Solution — Q5

Boolean filtering creates a condition that returns `True` or `False`
for every row.

Only rows where the condition is `True` are returned.

This is one of the most important operations in Data Analysis.
```

### Code Cell

```python
print("Marks greater than 75:")
print(df[df["Marks"] > 75])

print("\nAttendance greater than 80:")

# Create Attendance for this exercise
df["Attendance"] = [82, 91, 88, 72, 79, 95, 65, 86]

print(df[df["Attendance"] > 80])

print("\nStudy Hours greater than 5:")

# Create Study_Hours for this exercise
df["Study_Hours"] = [5, 7, 8, 4, 6, 9, 3, 7]

print(df[df["Study_Hours"] > 5])

print("\nMarks below 40:")
print(df[df["Marks"] < 40])
```

---

# Q6. Multiple Conditions

### Markdown Cell

```markdown
## Solution — Q6

Multiple conditions can be combined using:

`&` → AND

`|` → OR

Each individual condition should be enclosed in parentheses.

This is important because Pandas uses bitwise operators for Series
conditions.
```

### Code Cell

```python
print("Marks > 70 AND Attendance > 80:")

result_1 = df[
    (df["Marks"] > 70) &
    (df["Attendance"] > 80)
]

print(result_1)

print("\nMarks > 85 OR Study Hours > 7:")

result_2 = df[
    (df["Marks"] > 85) |
    (df["Study_Hours"] > 7)
]

print(result_2)

print("\nAIML AND Marks > 70:")

result_3 = df[
    (df["Department"] == "AIML") &
    (df["Marks"] > 70)
]

print(result_3)
```

---

# Q7. `isin()` and `between()`

### Markdown Cell

```markdown
## Solution — Q7

`isin()` checks whether values belong to a specified collection.

`between()` checks whether numerical values fall within a specified
range.

These methods make filtering multiple categories or ranges easier.
```

### Code Cell

```python
print("AIML or CSE:")
print(
    df[df["Department"].isin(["AIML", "CSE"])]
)

print("\nMarks between 60 and 80:")
print(
    df[df["Marks"].between(60, 80)]
)

print("\nAttendance between 70 and 90:")
print(
    df[df["Attendance"].between(70, 90)]
)

print("\nAge between 20 and 22:")
print(
    df[df["Age"].between(20, 22)]
)
```

---

# Q8. Create New Columns

### Markdown Cell

```markdown
## Solution — Q8

New columns can be created by assigning a calculation to a new
column name.

We will create:

- Study_Minutes
- Passed
- Marks_Percentage

This is the beginning of Feature Engineering.
```

### Code Cell

```python
df["Study_Minutes"] = df["Study_Hours"] * 60

df["Passed"] = (
    df["Marks"] >= 40
).astype(int)

df["Marks_Percentage"] = df["Marks"]

df
```

---

# Q9. Feature Engineering

### Markdown Cell

```markdown
## Solution — Q9

We create `Performance_Score` by combining Marks and Attendance.

We then convert numerical marks into meaningful categories using
`np.select()`.

This is an example of Feature Engineering because new information
is derived from existing variables.
```

### Code Cell

```python
df["Performance_Score"] = (
    df["Marks"] * 0.7 +
    df["Attendance"] * 0.3
)

conditions = [
    df["Marks"] >= 80,
    df["Marks"] >= 60,
    df["Marks"] >= 40
]

choices = [
    "Excellent",
    "Good",
    "Average"
]

df["Performance_Level"] = np.select(
    conditions,
    choices,
    default="Needs Improvement"
)

df
```

---

# Q10. Rename and Drop Columns

### Markdown Cell

```markdown
## Solution — Q10

`rename()` changes column names.

`drop()` removes columns.

We will rename two columns and then remove `Age`.
```

### Code Cell

```python
df = df.rename(
    columns={
        "Marks": "Final_Marks",
        "Study_Hours": "Daily_Study_Hours"
    }
)

df = df.drop(
    columns=["Age"]
)

df
```

---

# Q11. Sorting

### Markdown Cell

```markdown
## Solution — Q11

`sort_values()` sorts rows based on column values.

`ascending=True` sorts from low to high.

`ascending=False` sorts from high to low.

Multiple columns can be supplied using a list.
```

### Code Cell

```python
print("Marks ascending:")
print(
    df.sort_values(
        by="Final_Marks"
    )
)

print("\nMarks descending:")
print(
    df.sort_values(
        by="Final_Marks",
        ascending=False
    )
)

print("\nAttendance descending:")
print(
    df.sort_values(
        by="Attendance",
        ascending=False
    )
)

print("\nDepartment and Marks:")
print(
    df.sort_values(
        by=["Department", "Final_Marks"],
        ascending=[True, False]
    )
)
```

---

# Q12. Ranking

### Markdown Cell

```markdown
## Solution — Q12

`rank()` assigns a rank to each value.

By using `ascending=False`, the highest mark receives Rank 1.

We can then sort by the new Rank column to display students
according to their performance.
```

### Code Cell

```python
df["Rank"] = df["Final_Marks"].rank(
    ascending=False,
    method="dense"
)

ranked_students = df.sort_values(
    by="Rank"
)

ranked_students
```

---

# Q13. Top and Bottom Students

### Markdown Cell

```markdown
## Solution — Q13

`nlargest()` returns rows containing the largest values.

`nsmallest()` returns rows containing the smallest values.

These are convenient when we only need a small number of top or
bottom records.
```

### Code Cell

```python
print("Top 3 students:")
print(
    df.nlargest(
        3,
        "Final_Marks"
    )
)

print("\nBottom 3 students:")
print(
    df.nsmallest(
        3,
        "Final_Marks"
    )
)

print("\nTop 5 based on attendance:")
print(
    df.nlargest(
        5,
        "Attendance"
    )
)

print("\nStudent with highest study hours:")
print(
    df.nlargest(
        1,
        "Daily_Study_Hours"
    )
)
```

---

# Q14. Missing Values

### Markdown Cell

```markdown
## Solution — Q14

We first create a copy of the DataFrame and intentionally introduce
missing values.

`isna()` identifies missing values.

`sum()` can then be used to count them.

We can also use `any(axis=1)` to identify rows containing at least
one missing value.
```

### Code Cell

```python
missing_df = df[
    [
        "Student_ID",
        "Name",
        "Final_Marks",
        "Attendance",
        "Daily_Study_Hours"
    ]
].copy()

missing_df.loc[1, "Final_Marks"] = np.nan
missing_df.loc[3, "Attendance"] = np.nan
missing_df.loc[5, "Daily_Study_Hours"] = np.nan

print("Missing values:")
print(missing_df.isna())

print("\nMissing count:")
print(missing_df.isna().sum())

print("\nMissing percentage:")
print(
    missing_df.isna().mean() * 100
)

print("\nRows containing missing values:")
print(
    missing_df[
        missing_df.isna().any(axis=1)
    ]
)

print("\nComplete rows:")
print(
    missing_df[
        missing_df.notna().all(axis=1)
    ]
)
```

---

# Q15. Handle Missing Values

### Markdown Cell

```markdown
## Solution — Q15

For numerical columns, we can use statistical methods to fill
missing values.

Here:

- Age-like variables can use median.
- Marks can use mean.
- Attendance can use median.

After filling the values, we verify whether missing values remain.
```

### Code Cell

```python
clean_df = missing_df.copy()

clean_df["Final_Marks"] = clean_df[
    "Final_Marks"
].fillna(
    clean_df["Final_Marks"].mean()
)

clean_df["Attendance"] = clean_df[
    "Attendance"
].fillna(
    clean_df["Attendance"].median()
)

clean_df["Daily_Study_Hours"] = clean_df[
    "Daily_Study_Hours"
].fillna(
    clean_df["Daily_Study_Hours"].median()
)

print(clean_df)

print("\nRemaining missing values:")
print(clean_df.isna().sum())
```

---

# Q16. Duplicate Data

### Markdown Cell

```markdown
## Solution — Q16

`duplicated()` identifies duplicate rows.

`drop_duplicates()` removes duplicate rows.

We first inspect duplicates and then remove them.
```

### Code Cell

```python
duplicate_df = pd.DataFrame({
    "Student_ID": [101, 102, 103, 103, 104, 105, 105],
    "Name": ["A", "B", "C", "C", "D", "E", "E"],
    "Marks": [78, 85, 92, 92, 67, 88, 88]
})

print("Duplicate mask:")
print(
    duplicate_df.duplicated()
)

print("\nDuplicate rows:")
print(
    duplicate_df[
        duplicate_df.duplicated()
    ]
)

print("\nNumber of duplicates:")
print(
    duplicate_df.duplicated().sum()
)

clean_duplicates = (
    duplicate_df.drop_duplicates()
)

print("\nAfter removing duplicates:")
print(clean_duplicates)
```

---

# Q17. Duplicate IDs

### Markdown Cell

```markdown
## Solution — Q17

A row may not be completely duplicated, but its Student_ID may be
duplicated.

We can use `subset` to specify which column determines uniqueness.

`keep="first"` keeps the first record.

`keep="last"` keeps the last record.

`keep=False` identifies every record belonging to a duplicated group.
```

### Code Cell

```python
duplicate_ids = pd.DataFrame({
    "Student_ID": [101, 102, 103, 103, 104, 105, 105],
    "Name": ["A", "B", "C", "C Updated", "D", "E", "E Updated"],
    "Department": [
        "AIML", "CSE", "AIML", "AIML",
        "ECE", "CSE", "CSE"
    ],
    "Marks": [78, 85, 92, 95, 67, 88, 91]
})

print("Duplicated Student IDs:")
print(
    duplicate_ids[
        duplicate_ids.duplicated(
            subset=["Student_ID"],
            keep=False
        )
    ]
)

print("\nKeep first:")
print(
    duplicate_ids.drop_duplicates(
        subset=["Student_ID"],
        keep="first"
    )
)

print("\nKeep last:")
print(
    duplicate_ids.drop_duplicates(
        subset=["Student_ID"],
        keep="last"
    )
)

print("\nRemove all duplicated IDs:")
print(
    duplicate_ids.drop_duplicates(
        subset=["Student_ID"],
        keep=False
    )
)
```

---

# Q18. GroupBy — Student Analysis

### Markdown Cell

```markdown
## Solution — Q18

`groupby()` divides the data into groups.

We can then apply aggregation functions to each group.

Here we group students by Department and calculate:

- Average marks
- Average attendance
- Total study hours
- Minimum marks
- Maximum marks
- Student count
```

### Code Cell

```python
group_summary = (
    df
    .groupby("Department")
    .agg(
        Average_Marks=("Final_Marks", "mean"),
        Average_Attendance=("Attendance", "mean"),
        Total_Study_Hours=("Daily_Study_Hours", "sum"),
        Minimum_Marks=("Final_Marks", "min"),
        Maximum_Marks=("Final_Marks", "max"),
        Student_Count=("Student_ID", "count")
    )
    .reset_index()
)

group_summary
```

---

# Q19. GroupBy with Multiple Columns

### Markdown Cell

```markdown
## Solution — Q19

Multiple columns can be supplied to `groupby()`.

We will create a Year column and then group by:

- Department
- Year

Multiple aggregations can then be calculated for every group.
```

### Code Cell

```python
df["Year"] = [
    "First",
    "First",
    "Second",
    "Second",
    "Third",
    "Third",
    "First",
    "Second"
]

multi_group_summary = (
    df
    .groupby(["Department", "Year"])
    .agg(
        Average_Marks=("Final_Marks", "mean"),
        Average_Attendance=("Attendance", "mean"),
        Maximum_Marks=("Final_Marks", "max"),
        Minimum_Marks=("Final_Marks", "min"),
        Student_Count=("Student_ID", "count")
    )
    .reset_index()
)

multi_group_summary
```

---

# Q20. Aggregation Using `agg()`

### Markdown Cell

```markdown
## Solution — Q20

`agg()` allows us to perform several calculations in a single
grouped operation.

Named aggregations allow us to give meaningful names to the
resulting columns.
```

### Code Cell

```python
department_summary = (
    df
    .groupby("Department")
    .agg(
        Average_Marks=("Final_Marks", "mean"),
        Median_Marks=("Final_Marks", "median"),
        Maximum_Marks=("Final_Marks", "max"),
        Minimum_Marks=("Final_Marks", "min"),
        Average_Attendance=("Attendance", "mean"),
        Total_Study_Hours=("Daily_Study_Hours", "sum"),
        Student_Count=("Student_ID", "count")
    )
    .reset_index()
)

department_summary
```

---

# Q21. `transform()` Feature Engineering

### Markdown Cell

```markdown
## Solution — Q21

`groupby().transform()` calculates a group-level statistic but
returns a value for every original row.

This makes it very useful for Feature Engineering.

Here, every student receives the average marks of their department.

We then calculate how far each student's marks are from that
department average.
```

### Code Cell

```python
df["Department_Average"] = (
    df
    .groupby("Department")["Final_Marks"]
    .transform("mean")
)

df["Difference_From_Department_Average"] = (
    df["Final_Marks"] -
    df["Department_Average"]
)

df[
    [
        "Student_ID",
        "Department",
        "Final_Marks",
        "Department_Average",
        "Difference_From_Department_Average"
    ]
]
```

---

# Q22. Combining DataFrames

### Markdown Cell

```markdown
## Solution — Q22

The three datasets share `Student_ID`.

Therefore, `merge()` can be used to combine them.

We first merge Student Information with Academic Information.

Then we merge the Course Information into the resulting DataFrame.
```

### Code Cell

```python
student_information = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["A", "B", "C", "D"],
    "Department": ["AIML", "CSE", "AIML", "ECE"]
})

academic_information = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Marks": [78, 85, 92, 67],
    "Attendance": [82, 91, 88, 76]
})

course_information = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Course": [
        "Machine Learning",
        "Data Science",
        "Deep Learning",
        "Python"
    ]
})

student_academic = pd.merge(
    student_information,
    academic_information,
    on="Student_ID",
    how="inner"
)

final_student_data = pd.merge(
    student_academic,
    course_information,
    on="Student_ID",
    how="inner"
)

final_student_data
```

---

# Q23. Join Types

### Markdown Cell

```markdown
## Solution — Q23

Different join types preserve different records.

We will create two DataFrames with overlapping and non-overlapping
Student IDs.

Then we will perform:

- Inner join
- Left join
- Right join
- Outer join

Finally, we will inspect the number of rows and missing values.
```

### Code Cell

```python
left_df = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["A", "B", "C", "D"]
})

right_df = pd.DataFrame({
    "Student_ID": [103, 104, 105, 106],
    "Marks": [78, 85, 92, 88]
})

inner_join = pd.merge(
    left_df,
    right_df,
    on="Student_ID",
    how="inner"
)

left_join = pd.merge(
    left_df,
    right_df,
    on="Student_ID",
    how="left"
)

right_join = pd.merge(
    left_df,
    right_df,
    on="Student_ID",
    how="right"
)

outer_join = pd.merge(
    left_df,
    right_df,
    on="Student_ID",
    how="outer"
)

print("INNER JOIN")
print(inner_join)
print("Rows:", len(inner_join))

print("\nLEFT JOIN")
print(left_join)
print("Rows:", len(left_join))
print("Missing values:")
print(left_join.isna().sum())

print("\nRIGHT JOIN")
print(right_join)
print("Rows:", len(right_join))
print("Missing values:")
print(right_join.isna().sum())

print("\nOUTER JOIN")
print(outer_join)
print("Rows:", len(outer_join))
print("Missing values:")
print(outer_join.isna().sum())
```

---

# Q24. Real-Life Titanic Analysis

### Markdown Cell

```markdown
## Solution — Q24

The Titanic dataset is a real-world dataset containing information
about passengers aboard the Titanic.

We will perform several Pandas operations:

- Data inspection
- Missing-value analysis
- Sorting
- GroupBy
- Feature Engineering
- Duplicate detection

The dataset can be loaded from a local Kaggle download or from
the Kaggle API setup used earlier in the course.
```

### Code Cell

```python
# Load Titanic dataset
# Change the path if your Kaggle dataset is stored elsewhere.

titanic = pd.read_csv(
    "/content/titanic.csv"
)

print("Shape:")
print(titanic.shape)

print("\nMissing values:")
print(titanic.isna().sum())

print("\nMissing percentages:")
print(
    titanic.isna().mean() * 100
)

print("\nTop 10 passengers by Fare:")
print(
    titanic.nlargest(
        10,
        "Fare"
    )
)

print("\nSurvival rate by Passenger Class:")
print(
    titanic
    .groupby("Pclass")["Survived"]
    .mean()
)

print("\nSurvival rate by Gender:")
print(
    titanic
    .groupby("Sex")["Survived"]
    .mean()
)

print("\nSurvival rate by Class and Gender:")
print(
    titanic
    .groupby(["Pclass", "Sex"])["Survived"]
    .mean()
)

print("\nAverage Fare by Passenger Class:")
print(
    titanic
    .groupby("Pclass")["Fare"]
    .mean()
)

print("\nAverage Age by Passenger Class:")
print(
    titanic
    .groupby("Pclass")["Age"]
    .mean()
)

# Feature Engineering
titanic["Family_Size"] = (
    titanic["SibSp"] +
    titanic["Parch"] +
    1
)

titanic["Fare_Per_Person"] = (
    titanic["Fare"] /
    titanic["Family_Size"]
)

titanic["Age_Group"] = pd.cut(
    titanic["Age"],
    bins=[0, 12, 18, 60, np.inf],
    labels=[
        "Child",
        "Teenager",
        "Adult",
        "Senior"
    ]
)

print("\nTitanic with engineered features:")
print(
    titanic[
        [
            "PassengerId",
            "Age",
            "Family_Size",
            "Fare",
            "Fare_Per_Person",
            "Age_Group"
        ]
    ].head()
)

print("\nPassengers sorted by Fare:")
print(
    titanic.sort_values(
        by="Fare",
        ascending=False
    ).head()
)

print("\nDuplicate rows:")
print(
    titanic.duplicated().sum()
)
```

---

# Q25. Complete Pandas Data Science Challenge

### Markdown Cell

```markdown
## Solution — Q25

This final exercise combines the major Pandas concepts learned
throughout the course.

We will:

1. Generate a synthetic student dataset.
2. Inspect the dataset.
3. Introduce missing values.
4. Handle missing values.
5. Check and remove duplicates.
6. Create engineered features.
7. Perform sorting and ranking.
8. Perform GroupBy analysis.
9. Create department-level features.
10. Prepare `X` and `y` for Machine Learning.

The final structure will be:

X → Features

y → Target

The target will be `Passed`.
```

### Code Cell

```python
# ============================================================
# STEP 1 — CREATE SYNTHETIC DATASET
# ============================================================

np.random.seed(42)

n = 100

students = pd.DataFrame({
    "Student_ID": range(1001, 1001 + n),

    "Name": [
        f"Student_{i}"
        for i in range(1, n + 1)
    ],

    "Age": np.random.randint(
        18,
        25,
        n
    ),

    "Department": np.random.choice(
        ["AIML", "CSE", "ECE", "IT"],
        n
    ),

    "Year": np.random.choice(
        ["First", "Second", "Third", "Fourth"],
        n
    ),

    "Study_Hours": np.round(
        np.random.uniform(2, 10, n),
        2
    ),

    "Attendance": np.round(
        np.random.uniform(50, 100, n),
        2
    ),

    "Previous_Score": np.round(
        np.random.uniform(40, 100, n),
        2
    )
})


# ============================================================
# STEP 2 — GENERATE FINAL SCORE
# ============================================================

students["Final_Score"] = np.round(
    (
        students["Study_Hours"] * 4 +
        students["Attendance"] * 0.25 +
        students["Previous_Score"] * 0.45
    ),
    2
)

# Keep scores within a realistic range
students["Final_Score"] = students[
    "Final_Score"
].clip(0, 100)


# ============================================================
# STEP 3 — DATA INSPECTION
# ============================================================

print("First 5 rows:")
print(students.head())

print("\nLast 5 rows:")
print(students.tail())

print("\nShape:")
print(students.shape)

print("\nColumns:")
print(students.columns.tolist())

print("\nData Types:")
print(students.dtypes)

print("\nDescriptive Statistics:")
print(students.describe())


# ============================================================
# STEP 4 — INTRODUCE MISSING VALUES
# ============================================================

students.loc[5, "Attendance"] = np.nan
students.loc[15, "Previous_Score"] = np.nan
students.loc[25, "Study_Hours"] = np.nan
students.loc[35, "Final_Score"] = np.nan

print("\nMissing values:")
print(students.isna().sum())

print("\nMissing percentages:")
print(
    students.isna().mean() * 100
)


# ============================================================
# STEP 5 — HANDLE MISSING VALUES
# ============================================================

students["Attendance"] = students[
    "Attendance"
].fillna(
    students["Attendance"].median()
)

students["Previous_Score"] = students[
    "Previous_Score"
].fillna(
    students["Previous_Score"].median()
)

students["Study_Hours"] = students[
    "Study_Hours"
].fillna(
    students["Study_Hours"].median()
)

students["Final_Score"] = students[
    "Final_Score"
].fillna(
    students["Final_Score"].median()
)


# ============================================================
# STEP 6 — CHECK DUPLICATES
# ============================================================

print("\nDuplicate rows:")
print(
    students.duplicated().sum()
)

students = students.drop_duplicates()


# ============================================================
# STEP 7 — FEATURE ENGINEERING
# ============================================================

students["Study_Minutes"] = (
    students["Study_Hours"] * 60
)

students["Performance_Score"] = (
    students["Final_Score"] * 0.7 +
    students["Attendance"] * 0.3
)

conditions = [
    students["Final_Score"] >= 80,
    students["Final_Score"] >= 60,
    students["Final_Score"] >= 40
]

choices = [
    "Excellent",
    "Good",
    "Average"
]

students["Performance_Level"] = np.select(
    conditions,
    choices,
    default="Needs Improvement"
)

students["Passed"] = (
    students["Final_Score"] >= 40
).astype(int)


# ============================================================
# STEP 8 — DEPARTMENT AVERAGE
# ============================================================

students["Department_Average"] = (
    students
    .groupby("Department")["Final_Score"]
    .transform("mean")
)

students["Difference_From_Department_Average"] = (
    students["Final_Score"] -
    students["Department_Average"]
)


# ============================================================
# STEP 9 — TOP 10 STUDENTS
# ============================================================

top_10 = students.nlargest(
    10,
    "Final_Score"
)

print("\nTop 10 Students:")
print(
    top_10[
        [
            "Student_ID",
            "Name",
            "Department",
            "Final_Score"
        ]
    ]
)


# ============================================================
# STEP 10 — BOTTOM 10 STUDENTS
# ============================================================

bottom_10 = students.nsmallest(
    10,
    "Final_Score"
)

print("\nBottom 10 Students:")
print(
    bottom_10[
        [
            "Student_ID",
            "Name",
            "Department",
            "Final_Score"
        ]
    ]
)


# ============================================================
# STEP 11 — GROUPBY ANALYSIS
# ============================================================

department_analysis = (
    students
    .groupby("Department")
    .agg(
        Average_Final_Score=(
            "Final_Score",
            "mean"
        ),

        Average_Attendance=(
            "Attendance",
            "mean"
        ),

        Student_Count=(
            "Student_ID",
            "count"
        )
    )
    .reset_index()
)

print("\nDepartment Analysis:")
print(department_analysis)


# ============================================================
# STEP 12 — FIND BEST DEPARTMENT
# ============================================================

best_department = (
    department_analysis
    .sort_values(
        by="Average_Final_Score",
        ascending=False
    )
    .iloc[0]
)

print("\nDepartment with highest average Final Score:")
print(best_department)


# ============================================================
# STEP 13 — MACHINE LEARNING FEATURES
# ============================================================

X = students[
    [
        "Study_Hours",
        "Attendance",
        "Previous_Score",
        "Performance_Score",
        "Department_Average"
    ]
]

y = students["Passed"]


# ============================================================
# STEP 14 — FINAL ML CHECKS
# ============================================================

print("\nFeature Matrix X:")
print(X.head())

print("\nTarget y:")
print(y.head())

print("\nX Shape:")
print(X.shape)

print("\ny Shape:")
print(y.shape)

print("\nMissing values in X:")
print(X.isna().sum())

print("\nMissing values in y:")
print(y.isna().sum())

print("\nTarget distribution:")
print(y.value_counts())
```

---

# Final Pandas Practice Summary

These 25 solutions collectively cover the Pandas concepts from the course:

# Pandas — Course Conclusion

Pandas is one of the most important Python libraries for Data Science.

Throughout this section, we learned how to work with structured
datasets from the point of loading and inspecting data to preparing
features for Machine Learning.

---

## What We Covered

### 1. DataFrame Fundamentals

We learned how to:

- Create DataFrames
- Inspect DataFrames
- Understand rows and columns
- Check shape
- Check data types
- Generate statistical summaries

---

### 2. Data Selection

We learned:

- Single-column selection
- Multiple-column selection
- `loc[]`
- `iloc[]`
- Boolean filtering
- Multiple conditions
- `isin()`
- `between()`

These operations allow us to extract the exact data required for
analysis.

---

### 3. Data Transformation

We learned how to:

- Create new columns
- Modify existing columns
- Rename columns
- Remove columns
- Remove rows
- Insert columns
- Reorder columns
- Create calculated features

These operations form the foundation of Feature Engineering.

---

### 4. Missing Data

We learned how to:

- Detect missing values
- Count missing values
- Calculate missing-value percentages
- Identify incomplete records
- Remove missing values
- Fill missing values
- Use mean imputation
- Use median imputation
- Use mode imputation
- Use forward fill
- Use backward fill

We also learned that missing-value treatment is a Data Science
decision rather than simply a coding operation.

---

### 5. Sorting and Ranking

We learned:

- `sort_values()`
- `sort_index()`
- Ascending sorting
- Descending sorting
- Multi-column sorting
- `rank()`
- `nlargest()`
- `nsmallest()`

These operations are useful for finding top-performing and
low-performing records.

---

### 6. Duplicate Data

We learned:

- `duplicated()`
- `drop_duplicates()`
- Detecting duplicate rows
- Detecting duplicate IDs
- Keeping the first occurrence
- Keeping the last occurrence
- Removing all duplicated records

Duplicate handling is an important part of Data Quality.

---

### 7. GroupBy and Aggregation

We learned:

- `groupby()`
- `sum()`
- `mean()`
- `median()`
- `min()`
- `max()`
- `count()`
- `size()`
- `agg()`
- Named aggregations
- `transform()`

These operations allow us to convert raw records into meaningful
group-level insights.

---

### 8. Combining Data

We learned how to combine multiple datasets using:

- `concat()`
- `merge()`
- `join()`
- Inner join
- Left join
- Right join
- Outer join
- Multiple-column joins

This is essential because real-world data is frequently distributed
across multiple files, tables, or systems.

---

# Pandas and Data Science

Pandas allows us to transform raw data into a form that can be
analyzed.

A typical workflow is:

Raw Dataset
↓
Load Data
↓
Inspect Data
↓
Clean Data
↓
Select Required Data
↓
Transform Data
↓
Feature Engineering
↓
Analyze Data
↓
Prepare Machine Learning Data

---

# Pandas and Machine Learning

Pandas is not itself a Machine Learning library.

Instead, it prepares the data that Machine Learning algorithms
will use.

For example:

```text
Raw Dataset
     ↓
Pandas
     ↓
Data Cleaning
     ↓
Feature Engineering
     ↓
X — Features
y — Target
     ↓
Machine Learning Algorithm
     ↓
Prediction